### ISSUE TITLE
Swiping a Card To Close Restarts From Beginning

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#10]
If I have say 8 apps open, and i close app 6, i am brought back to the first card as opposed to being moved to card 5 or card 7. Also, while the name of the card is correct at the bottom, the springdots shows the wrong position (ie Mail is the first card, i close one card - card 6 - i am brought back to Mail, it says Mail on the bottom, shows the correct icon, but the springdots shows its as the last card. As soon as i swipe one way or another, the springdots readjust appropriately).

Settings: 3 Cards, swipe to close, double tap to open

**Comment by grp** [comment]
Seems to work fine here, closed.
