### ISSUE TITLE
New good idea: Quick switch

### ISSUE THREAD

**Issue by sagitt** [rpetrich/ProSwitcher#100]
I have another new idea, Quick switch...

ProSwitcher actually have the cards like palm pre, ok... but sometimes is really boring explore cards when the user have a lot of apps opened... So, I have at home a Sony Ericsson Xperia X1i and i saw the "panels" interface, so why you don't add a button in bottom-right that change the view of cards? Normal view (cards) or Quick View (With multiple pages and 9 priview for page)... like normal panel view of X1!, maybe with a shake the user can change quickly the view.

what you think? :)

http://www.youtube.com/watch?v=KF5Bq7A4ysY

**Comment by grp** [comment]
No. Anybody else can fork it and do this, but I don't think we will :).

**Comment by rpetrich** [comment]
I like this idea, but it really doesn't fit into our design. I would encourage someone to fork to implement this :)

**Comment by grp** [comment]
I agree!
