### ISSUE TITLE
Show Available Mem/Rispring

### ISSUE THREAD

**Issue by mattoligy** [rpetrich/ProSwitcher#102]
Hey guys thanks for all your work so far this tweak is just wikid!

The only thing i would ask for and it is just a request, as i dont use sbs it would be great for me if there was an area when you open proswitcher where it will show you the available memory/memory used by current app (If possible) ie, under or above each card, say safari [135 - 19] ipod [135 - 15] not sure how much mem safari and ipod use on an average that was just a guess lol...

And also a respring  element somewhere would be super handy :-)

Thanks again guys i'm a big fan

Matt.

**Comment by mattoligy** [comment]
Thinking about it i dont think theres really much space to put the free mem info is there...!?!?

**Comment by grp** [comment]
This is what SBSettings is for?

**Comment by mattoligy** [comment]
I think it would be much better and easier to have it as part of proswitcher all in one place no messing around!? Wouldn't need sbs at all then lol

**Comment by rpetrich** [comment]
I like the idea in general, but I think we're going to postpone this one...

**Comment by grp** [comment]
This may be hard to implement again; requiring possibly a daemon and some mach ports hackery...not fun :(.

**Comment by mattoligy** [comment]
ok guys fair enough lol, how about the respring idea? Also i got an idea regarding the iPod card but i'll open a new thread...

**Comment by grp** [comment]
Just use SBSettings! :D

**Comment by subdii** [comment]
Humm what about a sbsettings card... As a different way of activating sbsettings..???

**Comment by grp** [comment]
respring is completed!

**Comment by mattoligy** [comment]
OMG wikid :-) was you able to show free memory somewhere?

**Comment by grp** [comment]
No.

You just respring by closing the SpringBoard card.
