### ISSUE TITLE
Single-tap to Activate as Default

### ISSUE THREAD

**Issue by thelatinist** [rpetrich/ProSwitcher#104]
Instead of double-tap to activate, single-tap to activate should be the default behavior.  This is more consistent with the iPhone GUI, and will be the behavior most new users will expect.

**Comment by grp** [comment]
That is what I thought: but not what Ryan did :P.

**Comment by thelatinist** [comment]
I really think this should be revisited.  This is completely out of keeping with the iPhone GUI, and in particular with the closest analogue to this action: switching windows in Safari.  It is completely counterintuitive, and the only way I even figured out how to do it was only by looking under settings. It seems to me that consistency with the GUI should be a priority.

**Comment by grp** [comment]
Fine, I switched it :P.

**Comment by thelatinist** [comment]
I'm sure the n00bs will thank you. Hope you don't think I was being deliberately difficult. I mean, it's not going to matter to me either way, now; just trying to help others.

**Comment by rpetrich** [comment]
In the interests of reducing support emails, I'll give in on this one
