### ISSUE TITLE
Triple home button click

### ISSUE THREAD

**Issue by eweezy** [rpetrich/ProSwitcher#105]
I love this app. Works flawlessly for me. One question though, would it be possible to add a "three click home button" option to invoke ProSwitcher? I would love this because I really like my phone favorites as the double click.

Thank you,
Eric

**Comment by grp** [comment]
libactivator request; not proswitcher :)

**Comment by eweezy** [comment]
should i re-post here: http://github.com/rpetrich/libactivator/issues ?

**Comment by rpetrich** [comment]
If you could. That will ensure it's not forgotten :)
