### ISSUE TITLE
App title and icon disappears when swiping to no app

### ISSUE THREAD

**Issue by jerryen** [rpetrich/ProSwitcher#108]
If you are on the left most card and swipe far enough to the left, the app title and icon will disappear. Same happens on the right most card.

**Comment by thelatinist** [comment]
I can confirm this.  The icon and label disappear as if you are swiping to another card, but do not return even when the card returns to center.  They return when you swipe to the previous card and then back.

**Comment by rpetrich** [comment]
Confirmed.

**Comment by rpetrich** [comment]
Committed a fix.
