### ISSUE TITLE
Activation Method: Short Home Button Hold

### ISSUE THREAD

**Issue by WYSE** [rpetrich/ProSwitcher#11]
Whenever i use the short home button hold it shows proswitcher for a second then closes right away

**Comment by Surenix** [comment]
Yeah... the hold time should be less and not do that :) I am getting this too

**Comment by biird** [comment]
Same here

**Comment by GabsNL** [comment]
Yes, me too. If you hold it for about 2 seconds it closes again. 3 seconds: stays open.
Should be fixed :)

**Comment by xXFR0STBYTEXx** [comment]
yeah it does the same for me as well.

**Comment by rpetrich** [comment]
Should be fixed in libactivator 0.9.1 and the upcoming ProSwitcher 0.7

**Comment by grp** [comment]
Confirmed fixed here, I like it :)
