### ISSUE TITLE
Icons Don't Fly Out When Opening an App

### ISSUE THREAD

**Issue by DannyNemer** [rpetrich/ProSwitcher#110]
Normally, when you would open an application from the SpringBoard, the icons animate by flying out in all directions. In ProSwitcher 0.7.5, however, this no longer happens. The app just pops up from the middle of the screen while the icons stay in place.

**Comment by verzel** [comment]
confirmed

**Comment by cruz123** [comment]
I have no idea why this was done?! Perhaps for performance purposes. The new springboard transition created by PS is really bugging me.

**Comment by swlody** [comment]
I know I was one of the three others that raised an issue on this

**Comment by grp** [comment]
Duplicate.
