### ISSUE TITLE
Feature Request: Ability to choose whether or not to background foreground app upon invoking ProSwitcher

### ISSUE THREAD

**Issue by Bripab007** [rpetrich/ProSwitcher#112]
Instead of immediately backgrounding the currently-running foreground app when ProSwitcher is invoked, why not just wait until the user chooses to switch to another app?  If the users invokes ProSwitcher, then dismisses it (by swipe or home button), then simply return to the currently-running app, without applying backgrounding.

**Comment by rpetrich** [comment]
I prefer the behaviour as-is.

**Comment by Bripab007** [comment]
It just seems that ProSwitcher could strengthen its case as a task manager, in addition to its already strong showing as an app backgrounder/switcher, if it were able to be invoked merely to view and/or close other currently-running apps, rather than forcing the user background the current app immediately.

That said, you're the developer, and I appreciate your (and the other dev's) quick responses and willingness to entertain new ideas :-)
