### ISSUE TITLE
Expanding springboard icons when loading apps

### ISSUE THREAD

**Issue by bcharleson** [rpetrich/ProSwitcher#113]
Hey,

Just want to say thanks so much for an amazing app that changes everything for the iPhone!

I wanted to report a small bug or change I noticed in .75 after updating from .73. 

When initially loading any app the springboard icons don't expand/explode like it does natively. The app just animates and loads up. But when the is closed, the opened app shrinks and closes with the springboard icons going back to their positions

Please look into that!!  

again, thanks for such an amazing app that changes eveything!

-Brandon

**Comment by rpetrich** [comment]
Yup, we got this backwards in .75. Will be fixed for next version

**Comment by grp** [comment]
Fixed, pushed.
