### ISSUE TITLE
Icon theming should be optional

### ISSUE THREAD

**Issue by zwaldowski** [rpetrich/ProSwitcher#114]
Related to issue #53; using the WinterBoard theme's icons should be an option.  As mentioned in the comments on issue 53, all the default apps and increasingly more App Store apps (since the introduction of 3.0 with Spotlight, even earlier with App Store apps that had Preference Panes) include an Icon-Small icon.  These almost always look better than a scaled down Icon.png, WinterBoard or not.  Additionally, many WinterBoard themes are too small for practical use (Suave, Matte Nano) or are too vague when among other icons (see Glasklart).

**Comment by grp** [comment]
Completed!
