### ISSUE TITLE
Wrong display after restoring: iPod, Rotation

### ISSUE THREAD

**Issue by jordibruin** [rpetrich/ProSwitcher#118]
First of all; great application! Adds so much usability to the iPhone!

I stumbled upon a few little bugs while using ProSwitcher with the iPod application. When I am listening to a song (http://farm3.static.flickr.com/2507/4206235414_ed638cf341_o.jpg ) and I open proswitcher, it will work great (http://farm3.static.flickr.com/2777/4206235750_7aeb567179_o.jpg ).

However, when I click on the application and pause (http://farm5.static.flickr.com/4020/4206236122_2972fcff78_o.jpg) the song some things go wrong. 

When I open proswitcher while a song is paused, (http://farm3.static.flickr.com/2590/4206236568_360f14b465_o.jpg ) and I click on the ipod again to open it, it will go to the song list screen (http://farm3.static.flickr.com/2643/4205485479_e96b417bb3_o.jpg ) instead of the paused ipod screen (http://farm5.static.flickr.com/4020/4206236122_2972fcff78_o.jpg )

Hope this is enough information, otherwise I would be more than willing to send you more!

Jordi

**Comment by rpetrich** [comment]
I've edited your report so that the libactivator issue is here: http://github.com/rpetrich/libactivator/issues/#issue/1

**Comment by rpetrich** [comment]
To get the snapshot we capture a snapshot as the application is deactivating and save that. That works well in most cases, but since the iPod application switches views right after it launches, we will have to use another trick to get the proper screenshot to display in the animation. The real question is, which screenshot should ProSwitcher show in the list, the before or after?

(A simpler test is to rotate the mail application sideways, then background and reopen it)

**Comment by rpetrich** [comment]
After investigating this, it looks like the OS cheats by having pre-baked images of the appropriate iPod views and by using the unfilled default image when restoring formerly rotated Mail/Safari apps. I think we can do better, but there is no definite right answer here :(

**Comment by jordibruin** [comment]
If you close the ipod application on the paused screen, and after that reopen it again (no backgrounding with proswitcher) it will also go to the list view. I guess it's not possible to automatically go to the ''now playing'' screen unless you'd implement a command to go from list view -> now playing whenever you reopen the application?

**Comment by grp** [comment]
This isn't even anywhere related to ProSwitcher, though live views will "fix" this :).

**Comment by jordibruin** [comment]
But seeing as live views are pretty much impossible on the current hardware.. right?

**Comment by rpetrich** [comment]
Live Views won't fix this because iPod, Mail and Safari change their view layout/orientation as soon as they're resumed from background. Live Views are possible on even the original iPhone (though it won't be quick)
