### ISSUE TITLE
Animation of application and screenshot do not coincide

### ISSUE THREAD

**Issue by thelatinist** [rpetrich/ProSwitcher#119]
When zooming, the application animation seems to zoom slower than the screenshot animation does.  The result is overlapping images and a very untidy animation with two status bars.  I managed to capture a screenshot mid-animation:

http://www.latinist.net/image/task.png

Note that this is not the same issue as #76 "StatusBar coming back too slow when opening an app."

**Comment by rpetrich** [comment]
There are only two views animating: the screenshot view and the statusbar view. What you've shown in the screenshot you attached is identical to issue #76

I'll keep this open in the hopes that you'll convince me otherwise :)

**Comment by thelatinist** [comment]
Sorry, I misinterpreted #76.  I thought he was talking about the overlap of the non-animated transparent statusbar from the springboard background.  Is that intentional, by the way?  Or is it a problem with z-index?

**Comment by grp** [comment]
Its fixed now.
