### ISSUE TITLE
Zoom Screen not correct.

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#12]
The zoom in animation when you double tap an app seems to use the first screenshot that was taken instead of the current one. So for Pandora i see the Pandora splash screen zoom in then it shows the actual current screen. Same with Flowchat. Not a functional problem, but looks ugly.

**Comment by rpetrich** [comment]
This is a general issue with Backgrounder since it doesn't capture the screenshot at all.
Since ProSwitcher does, it shouldn't be too difficult to replace the original image in the activate animation.

**Comment by grp** [comment]
Or, we could just zoom in the screenshot we are showing to full screen like multifl0w does it.

**Comment by GabsNL** [comment]
I don't know how rpetrich's idea would look but I already sugested the way multifl0w does it. In this video around 0:24 you can see what it could look like http://www.youtube.com/watch?v=9bj4jJnQYSE

**Comment by rpetrich** [comment]
I just committed a way of doing it that's even better :D
(with a little effort we should be able to get in-app activation working with the same animation)

**Comment by GabsNL** [comment]
[ProSwitcher 0.7.1]
Opening an app with in-app now zooms correctly (with a little bug).
Closing it with in-app still shows the stock animation + Opening ProSwitcher.
Can this be changed to full on zoom out or is that impossible to do?

**Comment by rpetrich** [comment]
It's on the todo list. We have the code partially written, but still need to calculate the metrics properly

**Comment by danzimm** [comment]
this seems to be fixed in .7.3

**Comment by GabsNL** [comment]
@Zimm
If you are revering to the OP's problem I don't know never noticed it.
As for the ones I've posted none of the animations were changed in 0.7.3

**Comment by rpetrich** [comment]
Proper in-app activation committed to unstable
