### ISSUE TITLE
Increased memory usage and gesture problem with latest beta

### ISSUE THREAD

**Issue by ttopac** [rpetrich/ProSwitcher#120]
Memory usage is increased noticably and "close app gesture" is not working as smooth as older beta. It sometimes hardly recognise the gesture and i need to do it one more time.

**Comment by rpetrich** [comment]
Nothing has changed in terms of memory management between 0.7.5 and 0.7.3; nor with the swipe to close gesture.

**Comment by ttopac** [comment]
I cannot reproduce gesture problem. Probably i misinterpret the situation. I'll test more about memory issue. Is it possible that there's a memory leak?

**Comment by grp** [comment]
Theoretically; but there is no major memory leaks.

**Comment by ttopac** [comment]
I'll test more and if i become sure about the memory issue i'll post here again.

**Comment by grp** [comment]
If you are "sure", at least help us reproduce it ;).

**Comment by ttopac** [comment]
Of course :)

**Comment by grp** [comment]
I'd say this isn't really a bug; plus memory management is a lot better now. Closed.
