### ISSUE TITLE
ProSwitcher/LibActivator

### ISSUE THREAD

**Issue by gjtech** [rpetrich/ProSwitcher#121]
ProSwitcher 0.7.5 crashes TwitBird (version 2.1) when the "Nearby Tweets" function is used. This function, by default, displays nearby tweets in a Google Maps window view. Backgrounder, installed by itself, does not crash TwitBird.

I've successfully replicated this issue with both of their paid versions of TwitBird.

**Comment by gjtech** [comment]
I guess this is more of a heads up as other apps with embedded maps functions may also crash.

**Comment by rpetrich** [comment]
Crash file?

**Comment by gjtech** [comment]
Sorry, I had no idea where to send it...

http://www.xdracco.net/board/viewtopic.php?f=8&t=55

**Comment by rpetrich** [comment]
Well, that's definitely a crash; can you use the Crash Reporter software in Cydia to get the human readable version?
<sub>the distant future...</sub>

**Comment by gjtech** [comment]
well, between then and now, you release 0.8 and it's not crashing.. that's promising. I'll report back, with proper logs, if it crashes again..

**Comment by gjtech** [comment]
Ok. Well, it crashed. Here is the crash log using crash reporter..

http://www.xdracco.net/board/viewtopic.php?p=59#p59

It's the 2nd post. 

Regards..

**Comment by rpetrich** [comment]
Doesn't look like our bug. Can you describe how to trigger it?

**Comment by gjtech** [comment]
Hi, Thanks for taking the time to respond.

Well, I have no background apps running (except mail and phone). I open TwitBird and go to "Nearby Tweets". It zooms into my region and starts a blue echo line starts spinning and little icons start popping up indicating tweets. It's random when it crashes. Sometimes the echo line will rotate 2 or 3 times and then crashes out right there. Other times I move the map and it crashes. Other times it doesn't crash.

They do have a free version if you want to investigate. But it may be that the maps function is doing multiple queries and thus consuming more memory thus crashing out. I dunno. Just an idea.

**Comment by grp** [comment]
What other extensions do you have installed?

**Comment by gjtech** [comment]
I'm not entirely sure. If there are any addition extensions installed, then an app from Cydia depended on it. I have WeatherIcon. qTweeter, Snapper installed Those are 3 "background" apps.  Not sure I can give you an exact answer without knowing exactly what packages you may be asking about.

Thanks
