### ISSUE TITLE
Springboard card to the left of the current card

### ISSUE THREAD

**Issue by bob92** [rpetrich/ProSwitcher#122]
Is it possible to have an always showing home screen card to the left of the current app card. This way, users can go to the home screen just by select and touching the corresponding card rather than pressing the home button twice, or invoking any other method to close out of pro switcher.

Plus, if taking a screenshot of the home screen is not possible, a static ( user themeable) image can be used to represent the home.

**Comment by rpetrich** [comment]
I like this idea, but it's too much work to get going before launch... perhaps later :)

**Comment by bob92** [comment]
Thanks so much for replying. You are making one of the best jailbreak apps for the iPhone.

**Comment by iNIKELIV** [comment]
yea i want this feature too.....i think you should make it after fixing bags.....its realy needed.

**Comment by iNIKELIV** [comment]
*bugs

**Comment by grp** [comment]
Almost completed!

**Comment by mattoligy** [comment]
Sweet, is this going to be where the respring option is?

**Comment by grp** [comment]
Yes, just close this card to respring.

**Comment by Neblinio** [comment]
Will the springboard card have a different color X and also a confirmation to prevent accidental resprings?

**Comment by grp** [comment]
Nope.

**Comment by Neblinio** [comment]
Can you please consider these features if they don't involve a big change in code?

**Comment by mattoligy** [comment]
I think a confirmation is unnecessary but I different color x would be cool...
