### ISSUE TITLE
App Name disappears

### ISSUE THREAD

**Issue by edmechem** [rpetrich/ProSwitcher#124]
When I'm on the first app, and swipe quickly to the right - the screen moves rightward, and then quickly springs back into view. So far, so good. But the app name doesn't come back with it - it disappears. Same thing when on last app, and swiping to the left.

Running ProSwitcher 0.75, on an iPhone 3GS running OS 3.1.

Also running latest versions of Kirikae, Backgrounder and OverBoard.

**Comment by rpetrich** [comment]
Duplicate
