### ISSUE TITLE
Single click activation (in app)

### ISSUE THREAD

**Issue by subdii** [rpetrich/ProSwitcher#125]
Single click activation (in app)

**Comment by grp** [comment]
1. Maybe.
2. Just use a background image.
3. Not really feasable.

**Comment by subdii** [comment]
I try using Background.png In com.collab.proswitcher and setting the options to theme .... But no go!

**Comment by GabsNL** [comment]
You need to put a ProSwitcherBackground.png inside SpringBoard.app to make it work :)

**Comment by subdii** [comment]
Cool thank you

**Comment by grp** [comment]
It will work with the first method for final release!

**Comment by subdii** [comment]
I changed this to a single request :)

**Comment by GabsNL** [comment]
I would love single tap activation :)
I don't want to assign it to double tap and short hold takes long (lol).
This would be perfect.

**Comment by rpetrich** [comment]
In final

**Comment by GabsNL** [comment]
Sorry for reopening, but is this feature still underway? (Become Home Screen isn't the same)

**Comment by mattoligy** [comment]
Is this in 1.0?

**Comment by GabsNL** [comment]
No, It's not.

**Comment by mattoligy** [comment]
Oh, ok , lol

**Comment by rpetrich** [comment]
Become Home Screen is the replacement for this feature.
