### ISSUE TITLE
Center tap to close when no apps are running

### ISSUE THREAD

**Issue by swlody** [rpetrich/ProSwitcher#126]
This is just a small feature request, but it would be nice, when no apps are running to be able to just top in the center of the screen when ProSwitcher is open to close it.

**Comment by rpetrich** [comment]
Agreed; this is a simple fix too

**Comment by Neblinio** [comment]
Also it would be nice if ProSwitcher got closed automatically just after you tap to close the last active application left. The current 0.8 version stays opened displaying the message "No Apps Running".

**Comment by jordibruin** [comment]
Made an issue on it Nebinio

**Comment by mattoligy** [comment]
I didnt think you could close all apps anyways? iPod Phone and Mail cant be closed can they? Not for me anyway lol...

**Comment by swlody** [comment]
there is an option for them not to show
