### ISSUE TITLE
SpringBoard app launch zoom is 'different'

### ISSUE THREAD

**Issue by edmechem** [rpetrich/ProSwitcher#127]
It's an aesthetic preference to be sure, and it may not be easily fixable -- but - I prefer the 'normal' (former) SpringBoard zoom when I launch an app, to the zoom that's happening now with ProSwitcher installed.

Know what I mean? Yes? Great. No? Lemme know, and I'll de-install (then re-install) ProSwitcher long enough to properly describe what I'm saying, if it's not inherently clear...

For things like this, perhaps the best solution is to make it a user pref, if easily doable.

Thanks.

**Comment by grp** [comment]
Seriously, this is the 7th time this has been posted, and it is fixed for the next release.

**Comment by rpetrich** [comment]
Another Duplicate. It's a bug; it's since been fixed.

**Comment by edmechem** [comment]
Sorry guys. I did a cursory search for the other bug I reported (also a dupe) and didn't notice any existing bug that was obviously the same. Sorry for the dupe, but on the bright side - we're using it, we're paying attention, and we're giving you feedback. Thanks!

**Comment by rpetrich** [comment]
Yup, keep filing them. We don't mind duplicates too much (well, I don't at least). They just waste a little time is all
