### ISSUE TITLE
PS Activation Animation Messed Up

### ISSUE THREAD

**Issue by jerryen** [rpetrich/ProSwitcher#129]
If the first time you activate PS is in-app, the current app won't be centered immediately in PS. It seems to scroll to it from the bottom left.

**Comment by rpetrich** [comment]
Yup, this one slipped through

**Comment by rpetrich** [comment]
Committed a fix; can you verify this on your device? (make sure what I've done is sane)

**Comment by rpetrich** [comment]
Verified as fixed in unstable
