### ISSUE TITLE
Hide ProSwitcher Icon similar to OverBoard

### ISSUE THREAD

**Issue by mathewrice** [rpetrich/ProSwitcher#131]
I don't think this is completely classified as a bug, but ProSwitcher does not have the ability currently to hide its icon like OverBoard does. This is something that is a nice advantage since the only purpose of the icon is to activate ProSwitcher which has many options on what can activate ProSwitcher that are stored in the settings.app app.

**Comment by grp** [comment]
Use SBSettings, kthxbai.

**Comment by mathewrice** [comment]
Can you tell me, does OverBoard use libhide (from SBSettings) to hide itself without a respring?

**Comment by rpetrich** [comment]
No, OverBoard doesn't use libhide; it uses something more... awesome!

**Comment by mathewrice** [comment]
That's exciting since I am not a fan of libhide and would love to see that implemented to ProSwitcher as well as with many other Apps/Tools. Is the magic of OverBoard icon hiding gonna find its way to ProSwitcher?

**Comment by rpetrich** [comment]
Perhaps; probably not until after 1.0 though
