### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by grp** [rpetrich/ProSwitcher#135]
Similar to CategoriesSB, we should post UIAlertView once installed to tell people they CAN use it outside of springboard and to check out settings.

Very important.

**Comment by GabsNL** [comment]
Yes, it should also say that they can theme the Background by adding ProSwitcherBackground.png to SpringBoard.app. A lot of people don't know this.

**Comment by grp** [comment]
That isn't how it will work in the final! (or even 0.9)
