### ISSUE TITLE
App launching bug

### ISSUE THREAD

**Issue by lifeexpired** [rpetrich/ProSwitcher#137]
Basically, when an app is loading and i try to invoke proswitcher using double tap it dosent appear, but if i tap home again straight after it backgrounds but dosent bring up proswitcher..

Ive disabled CategoriesSB but it didnt make any difference..

If you want more information, please specify in what area.

**Comment by dharris** [comment]
Well i use the swipe down feature. When an app is loading and you invoke backgrounding (i am using CategoriesSB) from the springboard, PS does not create a card right away. It will only show up once App is fully loaded. 

However I can invoke PS at any time during this no problem by swiping so maybe tied to the home button...
