### ISSUE TITLE
PS should quit when closing the last app instead of showing "no apps running''

### ISSUE THREAD

**Issue by jordibruin** [rpetrich/ProSwitcher#138]
If you manually close every application in PS it will now show ''no apps running''.

I'm suggesting that PS will close and show the springboard because the user can't do anything while on the ''no apps running'' screen, so they'd have to close it either way.

ps. this suggestion was made on the irc channel by Guiye

**Comment by Fes2000** [comment]
I agree

**Comment by grp** [comment]
Implemented as a setting!

**Comment by GabsNL** [comment]
Thank you chpwn! :)

**Comment by dactylo** [comment]
Is this in 1.1?  If so it's not working for me.  I've tried setting "Empty Tap to Close" to both on and off and I still have to click the "No Apps Running" after x'ing out the last app...

**Comment by grp** [comment]
Go under Settings -> Empty mode or whatever and choose auto-close or whatever. Its th ere.

**Comment by dactylo** [comment]
Oops it works if I set "Empty Style" to Disabled.  Thanks chpwn!!

It might be nice to see "No Apps Running" when you call up ProSwitcher and there are no apps running (tap to close).  But exit without seeing this if you X out the last app.  I don't know if this is possible.
