### ISSUE TITLE
Sound is playing while game is minimased

### ISSUE THREAD

**Issue by iNIKELIV** [rpetrich/ProSwitcher#140]
When i minimise any game with sound it continues to play sound....Please fix this.

**Comment by grp** [comment]
That is not a freaking bug.

**Comment by iNIKELIV** [comment]
And.....what should i do with it??? are you going to fix this? or it is only on my device?

**Comment by rpetrich** [comment]
That's just how backgrounding works; perhaps request this of ashikase's backgrounder (which performs the backgrounding)
