### ISSUE TITLE
new side-ways layout

### ISSUE THREAD

**Issue by playn-zz** [rpetrich/ProSwitcher#141]
if you like this layout then maybe there could be an option to choose between both?
its basically the same as what the "Dock" app on cydia is, but with the much sexier ProSwitcher style :p

here is Dock's layout
http://img710.imageshack.us/img710/6135/docklay.jpg

here is what ProSwitchers could be
http://img707.imageshack.us/img707/4826/pslayout.png

and the delete function would be the same as Dock (drag out to the other side of the screen and let go, similar to what PS has now but sideways) everything else would stay how it is
the app in focus would have a bigger view screen and the ones behind (on the top and bottom of the app in focus) would be smaller
the scrolling would also be very smooth but lock the app in focus into position when done spinning

**Comment by grp** [comment]
Anybody else can fork this and implement it, but otherwise, no.

**Comment by playn-zz** [comment]
thats alright, thanks for reading :)

**Comment by rpetrich** [comment]
Yeah, this is a good idea, but not suitable to be part of ProSwitcher
