### ISSUE TITLE
Swipe up to close two apps consecutively causes graphic glitch

### ISSUE THREAD

**Issue by sysrage** [rpetrich/ProSwitcher#142]
I'm seeing a bug. swipe up two cards in a row to close them and it gets stuck showing no card until you tap. Just did it like 6 times in a row with different apps. phone, mail, safari were open. I background weather and stocks. swipe up weather, it closes and goes to stocks. swipe up stocks and it closes but sits there on a blank screen until I tap

**Comment by GabsNL** [comment]
I can confirm this, will look like this: http://img130.imageshack.us/img130/2509/img0227.png

This is the same as issue 139.
