### ISSUE TITLE
settings crash with 0.8 update

### ISSUE THREAD

**Issue by fredzhuzhu** [rpetrich/ProSwitcher#143]
Just after installing the update, opening settings put the iphone in safe mode.

**Comment by grp** [comment]
Not a bug thing.

**Comment by fredzhuzhu** [comment]
so it's what if it's not a bug ?

I remove it and the settings works again .

It's not a bug it's a feature ;)

**Comment by rpetrich** [comment]
chpwn: have we determined the source of this crash? crashbugs == evil

fredzhuzhu: can you send a crash log using Crash Reporter?

**Comment by fredzhuzhu** [comment]
Finally I restored because I had to do it for officially sim unlock my iphone, and after restore I don't have the problem anymore.
