### ISSUE TITLE
Returning from lockscreen to currently running foreground app, status bar is black and ProSwitcher not responding

### ISSUE THREAD

**Issue by Bripab007** [rpetrich/ProSwitcher#145]
Left WhatsApp app running in foreground, came back to my desk, unlocked screen, swiped down from status bar and nothing happened. Then noticed status bar was black, not light grey. Then clicked home button to quit WhatsApp app, but nothing happened. Then doubled-clicked home, correctly launched camera, single clicked home, and it returned to WhatsApp, status bar still black. Performing respring cleared problem.

Have no idea how to replicate problem but will try to retrace steps.

**Comment by sysrage** [comment]
This sounds very much like an old Backgrounder bug that's been around for a long time. Many times, if you get a phone call while an app is backgrounded, when the call ends that backgrounded app more or less becomes your springboard. If you have SBSettings, you can kill the problem app through that and it'll return you to the springboard (or a re-spring like you already found). Annoying as hell bug. Wish it'd get fixed.

**Comment by Bripab007** [comment]
Well, the problem is, I couldn't invoke ProSwitcher or SBSettings from the now-black-colored status bar.  It was like the status bar was broken.

Secondly, the app I was running was not backgrounded; it was my currently-running foreground app that happened to be open when my screen went to sleep.  I received no phone calls, while the screen was locked, then went back to my phone, unlocked the screen, came back into WhatsApp and the problem occurred.

Lastly, I've been running Backgrounder along with Kirikae and Multifl0w for quite a while and never experienced this problem.
