### ISSUE TITLE
Page Dots Return After Swipe To Close

### ISSUE THREAD

**Issue by likwidfuzion** [rpetrich/ProSwitcher#146]
Reproducible on beta v0.8

My settings: everything is default/On in preferences except Close Button, Show Dock, and Page Dots are off
1. Invoke ProSwitcher
2. Swipe up on any card to close
3. The page dots return

**Comment by sstarr07** [comment]
This happens to me too, but when you close PS and activate it again, the page dots are gone. (Page dots are set to off)

**Comment by grp** [comment]
Should be fixed.
