### ISSUE TITLE
Home button press at springboard - Multi icon mover

### ISSUE THREAD

**Issue by mattoligy** [rpetrich/ProSwitcher#149]
When you select multiple icons to move on the springboard using MultiIconMover then press the home button to complete the move ProSwircher is selected and everything go's a bit all over the place lol...

Is there a way when "home button press at springboard" is selected it's not active when in wiggle mode!?

**Comment by mattoligy** [comment]
Ok i'v just discovered it is fine in wiggle mode anyway UNLESS pasting icons using MultiIconMover!! This seems to be a bug/conflict with MultiIconMover...

**Comment by rpetrich** [comment]
We're implementing this feature differently now (had to convince chpwn that taking over the home button was bad)

**Comment by mattoligy** [comment]
Oh ok, so i'm guessing this conflict with tweaks like multi icon mover wont be a problem n e more!? Matt

**Comment by rpetrich** [comment]
There shouldn't be a conflict now, no.
