### ISSUE TITLE
Not properly remembering which app selected

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#15]
If I run ProSwitcher, it pops up, I can swipe to the side to the 3rd app. Then if I tap the ProSwitcher icon again to hide it, then re-open it it's still on the 3rd app.

If I open ProSwitcher, swipe to the 3rd app, close it, run another app, close it, and re-run ProSwitcher, it puts me back at the first app on the list instead of the 3rd.

**Comment by grp** [comment]
Yes, this needs to get worked on.
