### ISSUE TITLE
Dimmed Status Bar

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#150]
When you update on the new version (newer than 0.8) when you respring to lockscreen, the status bar gets dimmed.

**Comment by GabsNL** [comment]
Isn't that a build in feature of SpringBoard?
I had that even before I got ProSwitcher installed.

**Comment by Surenix** [comment]
I am not sure.. I've only seen this now... I've installed many things and this is the only I've encountered this problem/situation.

**Comment by GabsNL** [comment]
Try uninstalling ProSwitcher and respring the exact same way. See if it still dims.
I can't seem to reproduce this problem (with ProSwitcher installed).
Could you post the way you resprang? (using Cyfia, terminal or sbsetting etc.) I wanna try it out my self.
