### ISSUE TITLE
Behind Apps (Zoom) not centered

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#151]
The apps that are behind the zoomed apps are not centered and it's bothering me :P

**Comment by sstarr07** [comment]
lol! you have an eye! but good one. I agree too.

**Comment by grp** [comment]
No idea what this means someone make a screenshot so I can fix.

**Comment by GabsNL** [comment]
Damn, yes I also noticed this.
Here's a screenshot: http://img691.imageshack.us/img691/631/bugr.png

**Comment by rpetrich** [comment]
Can someone list what settings they have enabled to trigger this bug?

**Comment by GabsNL** [comment]
@rpetrich
This only happens when you use "Zoom Active Card" in settings.
Tested it with PSWSnapshotInsets 40 - 80. All are not centered.
