### ISSUE TITLE
Sometimes does not use the Icon-Small.png

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#152]
[ProSwitcher 0.8 + libactivator 1.0]
As seen in the screenshot, for the icon next to the app name it doesn't grab the Icon-Small anymore.
Instead it scales the big icon down.
http://img190.imageshack.us/img190/1747/img0226.png

**Comment by grp** [comment]
It is in settnigs, "themed icons".

**Comment by GabsNL** [comment]
Oh, didn't know that did this, thanks :)
