### ISSUE TITLE
Zoom to long

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#154]
When you have both the Zooming function, Application Title and the Page Dots, the Zooming function seems to hit the Page Dots... making it look dirty. :P

**Comment by grp** [comment]
Then disable page dots or zoom. Not a bug, there is nowhere else for it to go :P.

**Comment by rpetrich** [comment]
I disagree, this could be smarter... the zoom animation could be tweaked as well

**Comment by Surenix** [comment]
Yeah... you can do it :)
