### ISSUE TITLE
Locking the springboard card to the left

### ISSUE THREAD

**Issue by ejoya** [rpetrich/ProSwitcher#155]
It will be great if the springboard card can be locked on the leftmost side for easy access.
thanks

**Comment by grp** [comment]
Duplicate.

**Comment by R1ck** [comment]
It would be even better if the springboard card would actually take you to your first homescreen page instead of just leaving you at the page you where on last. This would serve as a short cut to your first page when you have "press home once at springboard" activated for PS.

**Comment by rpetrich** [comment]
R1ck: no plans to implement that.
