### ISSUE TITLE
Using Proswitcher with Bosspaper yields wallpaperless "Springboard" card.

### ISSUE THREAD

**Issue by cruz123** [rpetrich/ProSwitcher#160]
[Ver. 1.0] When using Bosspaper to theme my springboard, The wallpaper never appears on the "Springboard" card in PS. The card shows my themed icons and theme, but the blue wallpaper I use Bosspaper for never shows up :(.

**Comment by cruz123** [comment]
It seems to also not work with Winterboard backgrounds. The "Springboard" Card just shows a black background.

**Comment by grp** [comment]
That's because the springboard background isn't actually part of SpringBoard's UI: it is behind even that. The black background on the card atm is just a hack so the card's bg isn't transparent! this will be hard to fix.

**Comment by bob92** [comment]
why not make the card have a user themeable image of the springboard  as an option. I think this is relatively easy to implement and offers prettier springboard images than a black one.

**Comment by grp** [comment]
Don't like it, don't use it. Ask Ryan: I'm not going to do that for sure :P.

**Comment by rpetrich** [comment]
In unstable branch ProSwitcher now reads from springboardsnapshot.png if available. We may add support for reading BossPaper and whatnot later if it's not too much work

**Comment by bob92** [comment]
Thanks :)
