### ISSUE TITLE
Rounded Corners mess up when sliding cards

### ISSUE THREAD

**Issue by sstarr07** [rpetrich/ProSwitcher#161]
LibActiviator 1.0, PreferenceLoader 1.2.1, ProSwitcher 1.0.

When you set any level of 'rounded corners' to cards, while sliding the cards you can see that it defaults to a rectangle or to its default size (0) and then comes back to user set roundness. 

EDIT: You can see the rectangular edges when slide to the right. Left stays rounded.

**Comment by rpetrich** [comment]
Duplicate.

Only occurs when active card zooming is enabled. Can't be fixed without replacing CoreAnimation's mask with something custom (which will use a lot more memory)

**Comment by sstarr07** [comment]
Even though this was marked as 'won't fix,' I'm happy that it was dealt with in the latest update. Thanks! Animation is very smooth when scrolling through cards.
