### ISSUE TITLE
"Become Home Screen" should be user defined

### ISSUE THREAD

**Issue by sstarr07** [rpetrich/ProSwitcher#162]
Hi, small request if can be implemented. When you enable Become Home Screen, can we have a choice of activation just as we have a choice of activating PS.

**Comment by grp** [comment]
Activation of what? You either have it as your home screen, or not, nothing else :/

**Comment by rpetrich** [comment]
Yeah, this request doesn't make any sense. Become Home Screen == activate ProSwitcher when exiting an app normally, or when unlocking lock screen
