### ISSUE TITLE
Springboard first

### ISSUE THREAD

**Issue by sagitt** [rpetrich/ProSwitcher#169]
Why you don'r add an option to have springboard card ever as first?

**Comment by grp** [comment]
Why don't we? Because its it a lot of work to do for free, thats why! anyway I'll do this for next release

**Comment by mattoligy** [comment]
Why don't you make proswitcher a paid app? It deserves it...

**Comment by rpetrich** [comment]
Completed in unstable branch. Will have to tear this code out once we add reordering.
