### ISSUE TITLE
Feature Request: Toggle to auto-background currently running app when 

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#17]
Once we're able to invoke ProSwitcher from within other apps, this would be EXTREMELY useful. If you're in an app, you bring up ProSwitcher, then launch an app from the dock, it should automatically background the current app you're in.

I can see this causing issues with certain apps, so it would probably be necessary to have a blacklist of apps you don't want auto-backgrounded.

**Comment by grp** [comment]
Planned and not in this way, so closed.
