### ISSUE TITLE
Sometimes overlaps the SBPageDots.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#170]
[ProSwitcher 1.0.1~b2 + libactivator 1.1.0~b3] [iPhone 3G]

Activation Methods: Short Hold Home Button and Single Press at SB.
Display: Page Dots, Show Default Apps, Swipe to close, empty style disabled
Cards visible: three
Taps to activate: one
Theming: Show Dock, Background transparent.
## Steps to reproduce this problem:

Press the home button ones with Become Home Screen enabled inside an app.
## Result/issue

The app page dots sometimes overlaps the SBPageDots.
It makes it look really messy.
SS: http://img109.imageshack.us/img109/826/img0238.png
SS2: http://img300.imageshack.us/img300/9949/img0359.png

**Comment by cruz123** [comment]
Confirmed. I experience this problem when activating PS from within an app.

**Comment by GabsNL** [comment]
Tested it some more and cruz123 is right, only happens with in-app activation.

**Comment by grp** [comment]
I'm going to remove our page dots soon, for some reason there are so many bugs :(.

Anyawy, I'll fix this next time I can.

**Comment by rpetrich** [comment]
I'm against removing the UIPageControl. I think it helpful and lets me know how many apps are open at a glance

**Comment by sysrage** [comment]
Agreed with Ryan.

**Comment by GabsNL** [comment]
Also agree with Ryan, having a quick overview of all your apps is nice. I know a friend of mine would die without it xD: http://yfrog.com/4im1ixj

**Comment by Mike11** [comment]
I still hope my feature request will get implemented in the future (which would also remove the dots but keep the apps overview, so I guess I second chpwn's and ryan's point ;)

App icons instead of dots:
http://github.com/rpetrich/ProSwitcher/issues#issue/89

**Comment by grp** [comment]
Completed!

**Comment by mattoligy** [comment]
Is this in the 1.0.1 b2 ??

**Comment by GabsNL** [comment]
Yes it still is.
http://img300.imageshack.us/img300/9949/img0359.png
Updated first post.

**Comment by grp** [comment]
If this still happens, its not getting fixed :/. Too much work!

**Comment by mattoligy** [comment]
Well that's pretty crap, part of ps I think and part of what gives ps a stock sb feel...

**Comment by grp** [comment]
I'm hoping its fixed now: I did a major push to try and fix it. However, if it _still_ is broken, I don't know what else to do!
