### ISSUE TITLE
Smaller App cards don't allow "swipe up to close".

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#171]
[ProSwitcher 1.0 + libactivator 1.0]
[iPhone 3G]

When making the App Cards smaller the "slide to close" gesture doesn't work anymore.
Also a native settings for making the Cards smaller would be nice. :)
SS: http://img693.imageshack.us/img693/4176/img0239.png

**Comment by rpetrich** [comment]
Not a native setting, so no guarantee it will get fixed. Also, would need to know what value you have set in the plist

**Comment by GabsNL** [comment]
rpetrich: NVM, seems it got fixed somehow.
Sorry for the inconvenience :)

**Comment by rpetrich** [comment]
weird :P
Closed

**Comment by grp** [comment]
Or not :p

**Comment by GabsNL** [comment]
I found the problem.
I switched off "Swipe to Close" in the settings pane.
Now, it's truly closed. :p
