### ISSUE TITLE
Moving icon in springboard causes ui glitch

### ISSUE THREAD

**Issue by ejoya** [rpetrich/ProSwitcher#174]
make the springboard in icon move state then run proswitcher. The icons will overlap proswitcher and you will have to push the home button to exit the edit icons then dock will be inaccessible.

icon move state is wherein you hold the icon to move it somewhere.

**Comment by rpetrich** [comment]
Rephrased: Entering ProSwitcher should either disable icon reorder mode, or not be possible when reorder mode is active.

**Comment by grp** [comment]
Fixed: ProSwitcher will now refuse to activate in reorder mode.
