### ISSUE TITLE
Rounded corner mask slow to be applied with zoom active card

### ISSUE THREAD

**Issue by sysrage** [rpetrich/ProSwitcher#175]
Not a real big deal, but if you turn on Zoom Active Card, when cards are switching from being zoomed or not they get a square edge for a short time then get the rounded corner mask again. Looks a little ugly. I'll probably keep zoom disabled anyway, so I don't really care, but if you want perfection you might want to resize both the screenshot and the mask at the same time (if possible) instead of doing the zoom, then re-applying mask.

**Comment by grp** [comment]
Not a bug, this is slow because of apple.

**Comment by rpetrich** [comment]
All of this is done by CoreAnimation on the GPU and unfortunately it doesn't animate masks properly when the view size changes :(

Short of reimplementing masks by drawing them manually (and doubling our memory use) I don't see any way around this
