### ISSUE TITLE
Missing status bar swipe activation methods in 1.0

### ISSUE THREAD

**Issue by sysrage** [rpetrich/ProSwitcher#176]
After upgrading to 1.0, I no longer see the status bar swiping activation methods. They still work, as I had swipe down status bar selected before upgrading and it still works. But the options aren't there in settings.

**Comment by grp** [comment]
Not a bug.

**Comment by sysrage** [comment]
How is this not a bug? Why would you remove those activation methods?

**Comment by rpetrich** [comment]
Removed on request of BigBoss. They will return at some point.
