### ISSUE TITLE
iPhone Freezes with Parking Mania

### ISSUE THREAD

**Issue by patelhiren** [rpetrich/ProSwitcher#177]
I have ProSwitcher set to launch on Home Button Short Hold. When I launch Parking Mania app and then try to background it by holding the Home Button nothing happens and the iphone freezes. I have to reboot the phone by holding the sleep/home button combination.

**Comment by patelhiren** [comment]
What more info can I provide regarding this issue?

**Comment by chronzz** [comment]
crash logs. use crash reporter in cydia

**Comment by patelhiren** [comment]
There are not crash logs. If you monitor syslog you will see that when the Parking Mania Game is open and I try to Background it by short holding the home button to bring up ProSwitcher the log reads SpringBoardVisible=1. Thats about it. But ProSwitcher is not visible and the iPhone needs to be rebooted. My feeling is that the ProSwitcher is just hidden behind the ParkingMania window.
