### ISSUE TITLE
Weather icon using liveweather 

### ISSUE THREAD

**Issue by heresjohnny** [rpetrich/ProSwitcher#178]
The weather app comes up with a ? instead of the temperature on the Springboard page of PS. The weather icon displays the temperature correctly on the actual Springboard. I'm using liveweather icon to keep the weather app updated.

**Comment by grp** [comment]
Not a bug, liveWeather obv. didn't start updating it yet as it only takes the screenshot at the first load of SpringBoard.

**Comment by heresjohnny** [comment]
So there's no way to "reset" the screenshot?

**Comment by rpetrich** [comment]
not without slowing the activation time of ProSwitcher

**Comment by heresjohnny** [comment]
What if when you switch the Springboard Page toggle off and then on again it takes a new screenshot of Springboard (therefore the weather icon would have updated)? Fair enough if this is too long winded and all. Thanks for the app anyway.

**Comment by rpetrich** [comment]
respring accomplishes that.

**Comment by heresjohnny** [comment]
Doesn't work, at least not for the weather icon issue. I switched the Springboard page off and then did a respring. I waited until the weather icon had a temperature showing instead of a question mark, and switched the Springboard page on. Still had the old screenshot (the one with a question mark).

**Comment by rpetrich** [comment]
Does the weather not show the proper display at startup? If so, it will display wrong in the snapshot.

**Comment by heresjohnny** [comment]
Yeh, it reloads at each respring/startup, after the screenshot has been taken I'm assuming. Annoying, but oh well.

**Comment by rpetrich** [comment]
I'm going to mark this as Won't Fix; we have implemented the option to set the SpringBoard image and I think that's sufficient.
