### ISSUE TITLE
"Become Home Screen" feature breaks zoom animation.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#182]
[ProSwitcher 1.0 + libactivator 1.0]
[iPhone 3G]

When you activate the "Become Home Screen" in settings and single press the HomeButton inside an app it sometimes skips the zoom out animation and just opens PSW. If you (the devs) only work on newer model iDevices you probably won't encounter this problem.

**Comment by grp** [comment]
Guys, stop claiming we only work on newer devices. I'd love to have a 3GS or an iPod 3G, but the truth is I just can't afford buying another device until we get around twice our donations :P.

Anyway, thats not a bug, its just the iPhone getting overloaded.

**Comment by GabsNL** [comment]
Oh, haha, I just meant that people on newer models probably never encounter this issue. I wasn't sure what type of iPhone/iTouch you guys use. I also tought it was my iPhone getting overloaded but I encounter it everytime even without having an app open. Setting the PSWSnapshotInset to 70 or higher fixes this for me so please don't remove this .plist line in an update. :)
