### ISSUE TITLE
Feature Req.: Single home button tap Activation method.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#185]
Title says it all. Was hoping "Become Home Screen" did this but that doesn't Background the app.
In this feature's absents I tried using Backgrounder.app to set ALL my apps to Always-enabled but that totally broke my Default.pngs. ;/ (probably not a PSW bug).

**Comment by grp** [comment]
Duplicate.

**Comment by R1ck** [comment]
Yeah, I was thinking about this too it would be so much easier and simple to just hit the home button and have the app your working on backgrounded and have PS come up.

**Comment by rpetrich** [comment]
The older iPhone models don't have enough RAM to keep more than a few applications alive at once. We won't be making "background everything" an option (because half of our users don't understand that having too many apps backgrounded is a bad thing)

**Comment by GabsNL** [comment]
One's again, I really don't see the problem in this. Even without this feature I'll still Background as many apps as without, it just makes my PSW experience faster and more streamlined IMO.

**Comment by rpetrich** [comment]
GabsNL: the problem is not with you; it's with them. I've added a PSWBecomeHomeScreenShouldBackground setting, but this won't make it into the Settings pane.

LibActivator has to be designed in such a way that it is impossible to "disable" any in-built functionality.

**Comment by GabsNL** [comment]
rpetrich: I do understand your point of view. This will probably cause an overflow of Issues relating to "ProSwitcher keeps crashing".
As a final cry out, perhaps you could add a message to the popup when you first install PSW (or update it) that you shouldn't background too many apps because it could cause crashes. I'm happy you are going to add it as a hidden .plist setting do.

Thank you for making ProSwitcher even better and for listening to the community :)
