### ISSUE TITLE
Issue with "Become Home Screen" feature

### ISSUE THREAD

**Issue by R1ck** [rpetrich/ProSwitcher#186]
There seems to be a bug when its on. Lets say your on safari and hit the home button it should only open ProSwitcher, it does but it closes right away taking you back to spring board. It only happens when your starting fresh backgrounding an app because it works fine after the second app.

 BTW is there a way you could add to this feature by making it background the app with only hitting the home button once without having to do anything else?

**Comment by grp** [comment]
Duplicate.

**Comment by R1ck** [comment]
Ok now I figured it out. The bug here is that if you sleep your phone and then wake it the "Become Home Screen" feature gets turned off only once. Because if you open PS again and go into your app then it works fine as long as you don't sleep the phone.

Hey Chpwn what do you mean by duplicate because you ask everyone the same thing, no offense tho. Thank you for your hard work BTW.
