### ISSUE TITLE
Downward swipe missing

### ISSUE THREAD

**Issue by ckong** [rpetrich/ProSwitcher#189]
The downward swipe activation option disappeared from the settings.  I think it went missing during the last upgrade of libactivtor but am not sure.  Since I had the beta installed, and was using it, it still works.  Only...there's no setting for it now.

Any comments anyone?

**Comment by chronzz** [comment]
yea bigboss asked them to remove it so he can incorporate libactivator with sbsettings

**Comment by mattoligy** [comment]
Sbsettings is ugly, that dude really isn't update friendly is he...

**Comment by ckong** [comment]
chronzz, thanks for the headsup.

**Comment by chronzz** [comment]
@ mattoligy BigBoss is one of the best iphone developers out there and yes he does update his software with every new library or api that comes to the iphone and there are hundreds of themes for sbsettings. also he provides all his apps for free.

**Comment by mattoligy** [comment]
Yes "one of" the best, I didn't say he wasn't all I'm saying is he has bad taste in GUI...  And yes I know it's free and I am grateful of course but I don't really use a lot of his apps!

**Comment by rpetrich** [comment]
Will be added back later. Also, this is a libactivator feature request so I'm closing it.
