### ISSUE TITLE
Small Bug: Double tap Issue

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#19]
This is incredibly minor but normally, I have double tap home set to go to search. When PS not enabled, I double tap home and get to search. I can then hit the home button once to get back to the first page of the springboard. With PS (and LIbact) enabled, i can no longer hit the home button once to get back to the first page of springboard (in the activation section, i have it activated by a swipe and nothing related to the home button is checked). Instead I have to swipe left.

Again, minor but not sure if it has broader implications if double tap is set to other apps/functions.

**Comment by grp** [comment]
Duplicate.
