### ISSUE TITLE
Controls for ipod

### ISSUE THREAD

**Issue by sagitt** [rpetrich/ProSwitcher#190]
You know that with double tap on home if there is a song playing in ipod open the music control popup. Maybe add a button for open it from appswitcher?

**Comment by rpetrich** [comment]
This is a good idea. I think I will use this solution for the general case in libactivator :)

**Comment by mattoligy** [comment]
Sweet :-)

**Comment by grp** [comment]
libactivator related though, so I'm going to close it here: re-open it on that tracker.
