### ISSUE TITLE
Bug: "Become Home Screen" feature

### ISSUE THREAD

**Issue by R1ck** [rpetrich/ProSwitcher#192]
The bug is that if you sleep your phone and then wake it, the "Become Home Screen" feature gets turned off only once. Because if you open PSW again and go into your app then it works fine as long as you don't sleep the phone.

Try backgrounding a few apps go into one of them (lets say the iPod) change the song sleep it. Then wake it and hit the home button it will show PSW but then it will close out right away.

**Comment by GabsNL** [comment]
I can confirm this. Thought is was my iPhone's slow speed but can reproduce it on iPod 3G with just one app open.
(Become Home Screen Feature on)
open Safari
background it
open it again
lock iPhone
unlock iphone
press homebutton
you'll get a weird fade in animation and afterwards PSW closes.
