### ISSUE TITLE
No Screenshot, App Icon, or App Name 2

### ISSUE THREAD

**Issue by ghost** [rpetrich/ProSwitcher#193]
Issue 30 seems to be back again in version 1.

To reproduce
1. Make sure the hold home for a short period setting is active
2. Launch Storm 8's World War (it happens on other apps not just this one)
3. Hold down to activate PS
4. Voila no screenshot, app name, icon etc.

To get the screenshot and that back either close PS and reopen it or close another app in PS.

**Comment by sysrage** [comment]
Yep, this did return. Happens with The Weather Channel, too.
