### ISSUE TITLE
How to Disable Swipe Activation Methods in 1.0?

### ISSUE THREAD

**Issue by tinetwork** [rpetrich/ProSwitcher#195]
swipe activation is not an option in 1.0, but it the preference is saved from 0.8, how do i disable it? 

it's interfering with SBSettings.

I need to revert to 0.8 to disable it, but i can't find it anywhere. Please help!!!

**Comment by grp** [comment]
This isn't a bug, but remove the libactivator settings and you should be fine.

**Comment by tinetwork** [comment]
Thanks for the quick response and for your help. How do I remove the libactivator settings?

**Comment by rpetrich** [comment]
Remove both /User/Library/Preferences/libactivator.plist and /User/Library/Caches/LibActivator/libactivator.plist and respring your device
