### ISSUE TITLE
Last app not as focus!

### ISSUE THREAD

**Issue by sagitt** [rpetrich/ProSwitcher#198]
Sometimes if i quit some apps, the last app will not show as focus!

http://img412.imageshack.us/img412/4285/img0016u.png

**Comment by sysrage** [comment]
Duplicate

http://github.com/rpetrich/ProSwitcher/issues#issue/139
http://github.com/rpetrich/ProSwitcher/issues#issue/142
http://github.com/rpetrich/ProSwitcher/issues#issue/153
