### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by novactavy** [rpetrich/ProSwitcher#199]
A favorites app card would be really great. Where we can put the most used apps
for fast open ( like kirikae but much better because proswitcher is the bomb!!!)

**Comment by novactavy** [comment]
Maybe the favorites should be located where the dock is
and it would be really great if we can add more than 4 and slide thru left or wright.

**Comment by rpetrich** [comment]
Perhaps someone should just come up with a scrollable dock...

**Comment by novactavy** [comment]
There is one but its vertical. I guess the name of the app is "Dock". But yes u r wright!!!

**Comment by sysrage** [comment]
Putting Stack on my dock gives me access to all the 'favorites' i need :D

**Comment by grp** [comment]
exactly.

**Comment by The6uest** [comment]
I'd also like to see "favorites" added. Either at the bottom or in a separate tab like Kirikae. I prefer to have the dock hidden when PS is running.

**Comment by grp** [comment]
Well, its a "Won't Fix", I see no need for favorites.

If the code is forked and updated to support favorites well, I will pull in the changes, but I won't be coding it.

**Comment by The6uest** [comment]
Yeah, I understand. I just thought I'd throw my opinion in there. The favorites is the main reason I still use Kirikae along with PS.  I may take a look at Stack and Dock to use with PS instead.

**Comment by grp** [comment]
I'm going to be releasing a paid product soon that should help people with this :).

**Comment by The6uest** [comment]
Oh yeah? I look forward to it! 

I'd like to see an app that replaces Push notifications too.. like GriP but one that works better.

**Comment by mattoligy** [comment]
@chpwn so what's this app ur working on? Give us a lil heads up?

**Comment by grp** [comment]
See my twitter, it's called Infinidock and should be out in the Cydia Store for $0.99 very soon!
