### ISSUE TITLE
Running slow

### ISSUE THREAD

**Issue by Fes2000** [rpetrich/ProSwitcher#200]
ProSwitcher lags in speed compared to multiflow. I think it is using too much memory.

**Comment by grp** [comment]
Can you provide more details? Memory (in MB) usage when performing the same tasks? What part is taking too much memory? ProSwitcher actually takes less memory than multifl0w unless it is actually displayed, in which case the factors are too great to be compared.

More info is needed to address this.

**Comment by BrandonHacks** [comment]
1.0 runs very smooth for me, but I do now use the unstable build which seems to use a little more. What bugs me about that is it seems to take a while for the app(proswitcher) to load up

**Comment by grp** [comment]
The latest unstable shouldn't be any different...

**Comment by BrandonHacks** [comment]
Hmm, I'm on 3G with 3.1.2 and the app load time is a big difference. I dont know why that is if it's not any different.

**Comment by grp** [comment]
What is "app load time"?

**Comment by GabsNL** [comment]
The time it takes to open an app.
@BrandonHacks This is probably due to you having more then one app in the background.

**Comment by BrandonHacks** [comment]
what I mean is that opening proswitcher takes a lot longer than 1.0 for me, And no I only run phone, ipod, safari, springboard card.
