### ISSUE TITLE
App stays backgrounded but does not show in PS

### ISSUE THREAD

**Issue by sstarr07** [rpetrich/ProSwitcher#204]
When app is closed by sliding a card up, the app stays backgrounded but does not appear in PS.

**Comment by likwidfuzion** [comment]
Confirmed. This happens when you set the "Become Home Screen" setting to "Background"

**Comment by GabsNL** [comment]
Can also confirm. Happens to me as well with Become Home Screen set to Background.

**Comment by grp** [comment]
Confirmed here too. Will fix now.

**Comment by grp** [comment]
Fixed, but very-uglily.

**Comment by rpetrich** [comment]
Cleaned up chpwn's language on this one :)
