### ISSUE TITLE
ProSwitcher SB icon reappears temporarily when changing Empty Style setting

### ISSUE THREAD

**Issue by likwidfuzion** [rpetrich/ProSwitcher#208]
In v1.0.1~b2
1. Hide the ProSwitcher icon using SBSettings
2. Change the Empty Style setting from Text to Blank or Disabled
3. The ProSwitcher icon reappears on the SB again
4. Respring and the icon hides again

Step 2 seems to trigger the bug

**Comment by rpetrich** [comment]
Not a bug. We will have our own Show Icon toggle like OverBoard
