### ISSUE TITLE
Zoom out animation

### ISSUE THREAD

**Issue by sstarr07** [rpetrich/ProSwitcher#209]
Possible to get back the zoom out animation when exiting an app to PS? The latest update kills the animation and it doesn't look right in terms of being 'smooth.'

**Comment by GabsNL** [comment]
Have the animations changed? Mine are the same on 1.0.1~b2.
Are you sure you're no running the modded "without animation" version that's floating around on the internet?

**Comment by sstarr07** [comment]
You're right, animations have not changed. I had to reinstall PS from Cydia. Sorry.
