### ISSUE TITLE
Sleep short hold locking phone

### ISSUE THREAD

**Issue by anethema** [rpetrich/ProSwitcher#211]
in 1.0 the short hold of the sleep/lock button worked fine. Now what happens is it begins to bring up proswitcher but the phone immediately locks. Since I wanted a hardware button assigned to proswitcher and my home button is full this is the only activation that works for me.

iPhone 3GS 3.1.2.

**Comment by grp** [comment]
ProSwitcher is not the cause, post to libactivator bug tracker.
