### ISSUE TITLE
activating PS and backgrounding an app sometimes showing first card instead of 'new' app

### ISSUE THREAD

**Issue by sysrage** [rpetrich/ProSwitcher#213]
I can't reproduce this every single time, but it happens more often than not when doing the following:

1) respring
2) as soon as phone comes back up, unlock
3) open stocks app
4) immediately activate PS

Most times, PS is now showing me the Mail app instead of the Stocks app. Sometimes I don't even have to re-spring. I've had it happen with other apps, but Stocks app seems to do it more often than the others I've tried. It also doesn't seem to happen if I let Stocks app fully load data and re-draw the screen. Might have something to do with PS opening while the screen is changing.

**Comment by grp** [comment]
If you exit an app before its loaded you can't background it, and since it isn't loaded it will stop loading. This is intended.

If you mean something else open a new issue.
