### ISSUE TITLE
Cards are getting smaller?

### ISSUE THREAD

**Issue by Mike11** [rpetrich/ProSwitcher#215]
Is it just me or are the cards smaller in 1.01-b2 in default mode? It looks like the empty spaces around the cards are getting bigger and bigger? Because of that it's getting harder to read the content of the cards. Maybe you could offer some "maximize card size" option with minimal spaces around the cards and no icon, title etc?

**Comment by rpetrich** [comment]
With "Zoom Active" card, enabled, the active card was overflowing its boundaries a bit, so I reduced the size. Without "Zoom Active Card" enabled, the size is as it was before.

**Comment by Mike11** [comment]
So I guess it's not possible to widen the boundaries for a bigger/more readable card especially in zoom mode)?
