### ISSUE TITLE
Mail card blank

### ISSUE THREAD

**Issue by Mike11** [rpetrich/ProSwitcher#216]
The mail card shows a blank card most of the time. It works for the first 1-2 times and then it's always blank until I restart mail.app. I didn't behave like this when ProSwitcher was in public beta, it changed somewhere around version 1.0. Is this a known bug? I have a 3.1.2 3GS with Exchange push.

**Comment by rpetrich** [comment]
ProSwitcher can't read the screenshot until Mail has been opened at least once; it should show it from then on until the next time you respring. Is this not the behaviour you are experiencing?

**Comment by Mike11** [comment]
No, it isn't. I narrowed it down to a reproducible scenario:

respring --> invoke ProSwitcher --> switch to mail (white card as expected) --> invoke ProSwitcher in mail --> select mail again (screenshot is there) --> invoke ProSwitcher in mail --> select mail --> invoke ProSwitcher --> blank card (transparent, only X and badge visible; app name and icon show below)  

After that I have to close and restart mail.app or do a respring to see a mail screenshot ever again in ProSwitcher.

Since it's an Exchange push account mail.app runs in the background waiting for mails and also checks everytime I switch to it. So of course I wouldn't expect to see the updates in the mail card, but the screenshot from the last time I opened mail should be there. And as I mentioned before, I can't remember having this problem pre v1.0

**Comment by The6uest** [comment]
I have this same problem but I don't have Exchange mail. Mail.app image shows up a few times but then it goes blank unless I respring or reatart mail.

**Comment by Mike11** [comment]
Bug's still there in ProSwitcher 1.01b3

**Comment by Mike11** [comment]
Bug's still there in ProSwitcher 1.01b4. If you need more info I'm happy to provide you with what I can. Keep up the good work!

**Comment by rpetrich** [comment]
By blank, you mean what? A missing screenshot? Text content, but chrome still visible? Something else?

**Comment by The6uest** [comment]
I sent you an email with a screenshot of the blank mail we are talking about. Maybe it could be a conflict with another app we have..?

**Comment by Mike11** [comment]
In my case the mail card, or to be more precise the screenshot itself of the mail app is missing. I see just a dimmed transparent background with an X in the upper left corner and the mail icon and title below (like normal). I can still tap inside the area where the screenshot should be to switch to the mail app. As I explained earlier this is easily reproducible for me (100%) and only happens with mail.app (at least as far as I can tell on my iPhone 3GS).

**Comment by The6uest** [comment]
Yeah, that's exactly how mine is. The screenshot I sent him shows it except I turned the X close icon off.

**Comment by Fes2000** [comment]
If the app name was in the center of each card, then a blank card wouldn't be a problem for me.

**Comment by The6uest** [comment]
Latest update still has this problem. Wonder what causes it to disappear.

**Comment by mattoligy** [comment]
I have started to experience this!! I will upload a ss!!

**Comment by mattoligy** [comment]
3GS 3.1.2 latest proswitcher rc from cydia!

http://i210.photobucket.com/albums/bb259/mattoligy/9885d056.jpg
