### ISSUE TITLE
Activator Settings - Slide on Status Bar

### ISSUE THREAD

**Issue by informsme** [rpetrich/ProSwitcher#221]
Can you please add back SLIDE IN on STATUS BAR as activator settings?
It is more easy compare on SLIDE in on BOTTOM SCREEN, because mostly light app will show status BAR.
Hence, it is easy to switch btw app compared DOUBLE TAP or HOLD on STATUS BAR.
When you perform double tap or hold on status bar, it always accidentally touch another button top on the app..

Thanks

**Comment by rpetrich** [comment]
This conflicts with SBSettings, so until BigBoss uses libactivator... no.
