### ISSUE TITLE
Springboard card not showing icons

### ISSUE THREAD

**Issue by allinone23** [rpetrich/ProSwitcher#222]
The sp card only shows some of the dock icons and nothing else.

**Comment by rpetrich** [comment]
It shows whatever the state of your icons was when SpringBoard started

**Comment by grp** [comment]
Not a bug...

**Comment by allinone23** [comment]
Well it constantly shows no icons on the springboard card. So somthing is not right. Where can I upload a screenshot?

**Comment by rpetrich** [comment]
Wherever you want. Post a link here.
