### ISSUE TITLE
Ran today's upgrade (PS and LibActivator) Now no activation methods presented

### ISSUE THREAD

**Issue by scirica** [rpetrich/ProSwitcher#224]
As soon as you released the updates to ProSwitcher and LibActivator I took the upgrade via Cydia. When I go to ProSwitcher/Activation Methods the page is completely empty. Was there a problem with the repo contents? How do I fix this?

I've tried to reinstall Libactivator from Cydia, but that did nothing.

**Comment by grp** [comment]
Fixed...
