### ISSUE TITLE
Newest update breaks tap to close

### ISSUE THREAD

**Issue by antsh** [rpetrich/ProSwitcher#225]
After the latest updates of libactivator and proswitcher, the tap to close proswitcher when nothing is running isn't working anymore. Pressing home button still works, but seems to be much slower to respond than in previous versions.

**Comment by grp** [comment]
Part of the scroll-anywhere fix broke this.

**Comment by grp** [comment]
Also breaks tap-to-next-card and co.

**Comment by grp** [comment]
Fixed.

**Comment by rpetrich** [comment]
chpwn: are you sure? I only fixed the tap to next and double-tap to start/end gestures, not tap to close.

**Comment by grp** [comment]
Fixed.
