### ISSUE TITLE
can't scroll to "double tap home" to invoke PS

### ISSUE THREAD

**Issue by ride79** [rpetrich/ProSwitcher#227]
just updated libactivator and proswitcher.

can't bring up PS with double tap. Anytime I go to settings-PS. As soon as I scroll to "double-tap" the settings crashes back to Springboard. Can change other settings though like hold status bar, swipe from bottom, etc..., just the double-tap is causing it to crash. Haven't installed any new programs, was working fine before this update.

**Comment by kabamodern** [comment]
I submitted the same issue. Very very strange...

**Comment by grp** [comment]
dupliate
