### ISSUE TITLE
Cannot use double-tap home button activation method - Causes springboard crash

### ISSUE THREAD

**Issue by kabamodern** [rpetrich/ProSwitcher#228]
I've installed all update for ProSwitcher and LibActivator. I've also completely uninstalled, rebooted, and reinstalled everything. I have nothing else using double-tap home button. When I go into Settings > Activator Settings > (choose any category) > Home Button > Double Press > it crashes to springboard. Same thing when I go to Settings > ProSwitcher > Activation Methods > when I try to scroll down to Home Button section it crashes to springboard.

Very, very strange. Please help!

**Comment by kabamodern** [comment]
Any updates on this?

**Comment by rpetrich** [comment]
Update to the latest libactivator; it handles gestures.

(also, including crash reports generated by kennytm's "Crash Reporter" greatly helps in solving bugs)
