### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by antsh** [rpetrich/ProSwitcher#229]
I think there might be a memory leak going on with the latest updates of proswitcher/libactivator. I don't have anywhere near the technical skill to pinpoint it, but it seems that after the latest update, the free memory on my 3.1.2 3GS seems to be getting smaller and smaller even when the phone is left at idle. This could be completely unrelated though, as I said I have no idea how to actually test if it is proswitcher/libactivator.

**Comment by sysrage** [comment]
I think this is correct. Normally I'm around 100mb free even after going without a respring or 'free memory' for a couple days.. After recent updates I was getting down around 30mb very quickly. I just disabled PS and LA and was gonna run like that awhile to make sure those are the culprits before posting something here. But since somebody already did....

**Comment by BrandonHacks** [comment]
yeah and after the update I'll have it in idle then I'll wake the iPhone up, when I slide to unlock it crashes to safe mode):

**Comment by sysrage** [comment]
I'm not sure this is PS/LA anymore. With them both disabled today my memory still dropped down to 40mb. I sure wish there was better memory monitoring available. Top sorted by rprvt just shows all the default apps on top (springboard, mobilemail, mobilesafari, phone, ipod..).. but if I kill safari and ipod apps it only gives me 20MB or so... kill mail for another 10 or so.. definitely looking better, but with both those closed i should be way above 72MB free..

**Comment by antsh** [comment]
After a day of using my iphone with PS/LA/Overboard installed, my memory leak issue has actually disappeared [as far as I can tell]. Also, rpetrich has posted a commit summary for a memory leak over at the libactivator github, so I believe there was a memory leak present in the latest beta. Maybe you have another dylib or something that is causing a memory leak?

**Comment by antsh** [comment]
Latest update to libactivator seemed to have fixed the memory leak for me. Keep up the great work!

**Comment by antsh** [comment]
Actually after about another day of use, there seems to still be a leak. It is much smaller now, however.

**Comment by rpetrich** [comment]
The only memory leak that was solved was a very small one (wouldn't even reach 10KB over a few months without a respring)

ProSwitcher requires some standard amount of memory to do it's magic, and then additional memory per active application, but none of my tests have shown any leaks.

A very unscientific test that users can perform:
1. Launch Notes
2. Background Notes
3. Activate ProSwitcher
4. Kill Notes
5. Deactivate ProSwitcher
6. Check SpringBoard's memory use
7. Rinse and repeat
After the first few runs, memory use should remain static (there are caches and whatnot that have to be populated, so don't compare against a "fresh" SpringBoard)

**Comment by antsh** [comment]
It could very well not have been ProSwitcher, I'll do some more thorough testing ASAP and get back to you. Thanks for the support.
