### ISSUE TITLE
Short Hold Home Button for Springboard

### ISSUE THREAD

**Issue by verzel** [rpetrich/ProSwitcher#230]
Feature request: When "Become Home Screen" is enabled, a short hold of the home button should bring the user to the springboard.  As it is now, if the user wants to open an app, they have to press the home button twice, and take care that it's not a double tap.  Introducing an option to hold the button for a short time to get to the springboard would eliminate this issue and make ProSwitcher more useful.

**Comment by grp** [comment]
Not related to ProSwitcher.
