### ISSUE TITLE
Tapping the sides of the screen no longer slides proswitcher

### ISSUE THREAD

**Issue by verzel** [rpetrich/ProSwitcher#232]
It used to be that I could tap the left or right side of the screen to slide between apps, or double tap to quickly go to the beginning or end of the app list. This no longer works in 1.0.1~b3.

**Comment by BrandonHacks** [comment]
Yeah I thought it was just me and that maybe I some how broke proswitcher.

**Comment by grp** [comment]
No, its part of a fix we did for something else.

**Comment by BrandonHacks** [comment]
Hmm:/ so are we going to see this again in a future update?

**Comment by grp** [comment]
Maybe.

**Comment by BrandonHacks** [comment]
I sure hope so(; off subject, but love the infinidock. first time I've paid for something in cydia(;

**Comment by grp** [comment]
Fixed.
