### ISSUE TITLE
not enough memory in device...

### ISSUE THREAD

**Issue by nadzsina** [rpetrich/ProSwitcher#234]
hello ...i`ve got a porblem while installing the proswitcher on my iphone 3g 3.0..it says that the "memory in the device is not enough" and the installation terminates suddenly...i`ve looked on the cydia->manage->storage and it shows that i`ve used 100% in the system...how can i fix this?how to free this system ?help me out please

**Comment by grp** [comment]
Uninstall some packages on the system partition, or use PwnageTool to get a bigger one.

**Comment by rpetrich** [comment]
Yeah, if you don't have enough space to install ProSwitcher (which is < 1MB) you seriously need to clean things up in order to keep device stability!
