### ISSUE TITLE
Proswitcher welcome screen shows up everytime i respring

### ISSUE THREAD

**Issue by alexling** [rpetrich/ProSwitcher#236]
hi, i have just updated proswitcher to 1.1.0~b4, and after respring i see a welcome box every time. Does anyone else have the same problem?

**Comment by rpetrich** [comment]
Does it go away if you change a setting in ProSwitcher's settings pane?

**Comment by Sveat** [comment]
Yes, every time I have welcome screen:(

**Comment by Judgejase** [comment]
Me too, report bug screen every respring

**Comment by Eddiekarl** [comment]
I also have this problem

**Comment by gems117** [comment]
Me too , i'v already got it T-T

**Comment by Rain1Maker** [comment]
I feel sorry that I upgrade it. Is they a way to remove it

**Comment by rpetrich** [comment]
Alpha/beta versions have this popup. It will be removed in final public releases, but there will be _no_ way to do so until then.
