### ISSUE TITLE
Here you are some suggestions for your Great App to get better!

### ISSUE THREAD

**Issue by m-elagdar** [rpetrich/ProSwitcher#237]
1-"Empty tap to close" isn't working since 1.0.1 B3 & B4 too.
2-Instead of disabling the app while there is no app running you can make it work for a second to let me make sure that the program didn't have a problem in starting.
3-"Status bar slide down is disabled since v1.0 although it was the easiest way to launch the program so if you pleased add it again

At the end thank you for your great app & I wish you good luck!

**Comment by grp** [comment]
None of these are not already duplicates or as designed.
