### ISSUE TITLE
Conflict with QuickDo?

### ISSUE THREAD

**Issue by alexling** [rpetrich/ProSwitcher#238]
I updated PS to 1.1.0~b4, and i find that when i use QuickDo to close an app, it doesn't quit other than background. It never happens when i use 1.1.0~b3 and previous versions.

**Comment by joeheathen** [comment]
I just updated to the latest version of libactivator (proswitcher wasn't updated) and now quickdo is MUCH more difficult to activate. I only use quckdo along the bottom (no status bar) and do not have proswitcher set to activate from bottom gestures. Uninstall of proswitcher confirms, and after reinstall it's almost impossible to raise the quickdo bar.

**Comment by alexling** [comment]
after updating to libactivator rc3 and public release 1.1.0, everything goes fine. :)
