### ISSUE TITLE
Closing app 'zoom out' animation intermittently missing

### ISSUE THREAD

**Issue by sysrage** [rpetrich/ProSwitcher#240]
Every once in awhile, when PS and LA are enabled, the zoom out animation that shows when you close an app is not seen. When the home button is tapped, the app sits there for a second doing nothing then disappears with no animation.

I have not found an exact consistent way to reproduce this issue. However, I see it at least twice a day when PS and LA are activated and I just went a full day with them both disabled and did not see the problem. I'll continue to try to find a consistent way to reproduce the problem, but please look into this. If there are any experiments you'd like me to try to narrow it down, let me know.

**Comment by grp** [comment]
not a bug

**Comment by sysrage** [comment]
how is this not a bug? it is most definitely a bug. I kept PS/LA disabled for 2 days and it never happened. re-enabled them and intermittently see it happening again.
