### ISSUE TITLE
Single tap on status bar?

### ISSUE THREAD

**Issue by dactylo** [rpetrich/ProSwitcher#249]
I wish the tap and hold didn't take so long to activate.  Is it technically possible to have an option that's closer to a single tap?  Maybe a "long tap"?  I'd still like to preserve a quick single tap to scroll to the top of a list.  Unless there was a way to let any list showing have the first single tap and activate with the second single tap.

(And thanks so much for writing this app- amazing!)

**Comment by rpetrich** [comment]
The statusbar is overloaded with a ton of different extensions trying to grab its events. I think this is a bad idea until some of the popular extensions switch to libactivator.
