### ISSUE TITLE
ProSwitcher 1.1 never pushed to repo?

### ISSUE THREAD

**Issue by antsh** [rpetrich/ProSwitcher#250]
Even though the lastest commit states that there was a 1.1 public release, bigboss is only showing 1.0 and your repo only has the latest beta before 1.1. Is there something up on my end, or was the 1.1 released never pushed?

**Comment by grp** [comment]
Pushed...

**Comment by rpetrich** [comment]
Sometimes it's not instant for public repos (we get confused as to who is supposed to send it to them, lol)

**Comment by antsh** [comment]
Haha no problem, not at all meant to rush you guys. I'm just spoiled by your quick turn around and the fact that I'm used to seeing it up instantly after a version bump is commited and automatically tweeted.
