### ISSUE TITLE
Close Button, Badges Disappear after Update

### ISSUE THREAD

**Issue by strtpls3** [rpetrich/ProSwitcher#269]
Hello,

  I'm running an non-winterboarded 3GS on 3.01.  Proswitcher 1.1 worked perfectly for me for months until an "update" notification popped up in cydia today.  I updated then reloaded cydia.  I thought it was strange that cydia still had an update notification for proswitcher.  Looking more closely I noticed that the version in the update is the same 1.1 that I had.  I tried using pro switcher and noticed that though show badges and show close button are turned on, neither option shows up when I use proswitcher now.  

I would appreciate any help you can offer with this issue.

Thanks,
Strtpls3

**Comment by ruitakim** [comment]
I have this same problem, running 3GS on 3.1.2 and I do have winterboard installed. Cydia is constantly saying that there is an update available too. 

Any help is appreciated, thanks!

**Comment by grp** [comment]
Do you guys have any extra repos? Possibly the illegal warez site beyouriphone?

**Comment by ruitakim** [comment]
Hi, thanks for the response, no I don't have any extra repos or beyouriphone installed.

The repos I have installed are Bigboss, iSpazio, ModMyi.com, Ste Packaging, Telsphoreo, and ZodTTD.

The update is coming from the Bigboss repo. (it says "from BigBoss (System)")

Tried updating in the morning and the problem fixed itself...thanks for whatever you did server side!

**Comment by rpetrich** [comment]
We'll chalk this up to a mystery!
