### ISSUE TITLE
Touchscreen unresponsive [iPad]

### ISSUE THREAD

**Issue by manualoverride** [rpetrich/ProSwitcher#274]
I've been using the public alpha for about an hour.  I've found that the touchscreen is unresponsive intermittently. The solution I've found is to activate ProSwitcher via the assigned method. This is interesting because although the screen seems unresponsive to swipes and icon taps, it will recognize swipes designated to activate PS (currently triggered by "swipe from bottom of screen). Thinking it might be a setting issue, I set the toggles to the same sequence as on my iphone 3G (with which i do not experience this issue) but the bug persists. Aside from that the app seems stable thus far. I look for to the final release and donating. Cheers.

**Comment by daytonlowell** [comment]
Same as issue 275 & 284.

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha2
