### ISSUE TITLE
no page navigation until proswticher activated

### ISSUE THREAD

**Issue by benp** [rpetrich/ProSwitcher#275]
using the new alpha: can't go to previous/next page in Springboard until I activate proswitcher with gesture.

**Comment by daytonlowell** [comment]
This is probably the same as issue 284

**Comment by daytonlowell** [comment]
..and 274

**Comment by Gucky17** [comment]
And 314

**Comment by rpetrich** [comment]
Committed a fix to HEAD. Will be released in 1.2a2.
