### ISSUE TITLE
Roation with pro switcher

### ISSUE THREAD

**Issue by Klaus385385** [rpetrich/ProSwitcher#277]
Card will not expand or auto rotate after going from landscape activation then rotating to portrait. Also will stay sometimes in the initial launch state. For example listening to music in landscape then activate pro switcher and then rotate to portrait and iPod stays in landscape when activated

**Comment by rpetrich** [comment]
Can you provide more detail? (and screenshots where appropriate)

**Comment by Klaus385385** [comment]
http://moby.to/fi3oky http://moby.to/pf8kkk

Here is the photos

So as you cannot see the preview autorotation fails by going from the settings in portrait then rotated to lanscape and the preview will not rotate k

**Comment by rpetrich** [comment]
This is as-designed

**Comment by Klaus385385** [comment]
Wow ok then hope later that may change

**Comment by rpetrich** [comment]
Maybe when 4.0 comes, and applications have support for setting the "background screenshots" will we possibly get support for this.
