### ISSUE TITLE
(1.2~alpha~1) Cards sometimes miss the lower half

### ISSUE THREAD

**Issue by moschlar** [rpetrich/ProSwitcher#279]
As you can see on the attached screenshots, sometimes after backgrounding a new app, the card left of it has a big black bar on its lower half. (After I made a screenshot it showed normal again :D)
And in one case, it was the current app, thats card didn't show up correctly.
Screenshots here: 
http://img64.imageshack.us/img64/3706/img0430.png
http://img507.imageshack.us/img507/679/img0429.png
http://img190.imageshack.us/img190/6803/img0428.png

Thx for your great work!

**Comment by rpetrich** [comment]
Interesting. On what hardware is this?

**Comment by moschlar** [comment]
It was on a 3GS, but it seens that you've already fixed it ;)
Thx!

**Comment by rpetrich** [comment]
I think this was related to the rounded corners bug. I will mark as completed :)
