### ISSUE TITLE
SBRotator Support

### ISSUE THREAD

**Issue by fretman92** [rpetrich/ProSwitcher#281]
On the iPhone, when ProSwitcher is showed up and you rotate your SpringBoard (thanks to SBRotator), some things kinda weird happen after a few SB rotations...
Cf screen-shots here http://hostimages.eu/images/photoqmq.jpg and http://hostimages.eu/images/photo2.jpg

Thanks for the support

**Comment by rpetrich** [comment]
Won't fix. Unless we receive patches to add this, I have no intention of adding support for SBRotator.
