### ISSUE TITLE
Backgrounded app screen flickers

### ISSUE THREAD

**Issue by Rainman99** [rpetrich/ProSwitcher#282]
Proswitcher 1.2 alpha running on 3GS 3.1.
Backgrounded app screens are flickering and partly disappearing on Alpha

**Comment by rpetrich** [comment]
Can you list the extensions you have installed? Any other details you feel might be relevant.

A screenshot/video would also be helpful

**Comment by Rainman99** [comment]
Hi rpetrich
What extensions are you talking about? I think too many to being listed but with 1.1 everything worked fine.

Bugs i noticed when upgrading from 1.1 to 1.2 alpha 1
1. Device freezes after installation respring
2. PS welcome screen freezes after respring and appears every time after each respring (see pic 1)
3. Backgrounded app screens are flickering (pic 2)

Can't show you the flickering of the backgrounded app screen cause everytime I take a screenshot, screen shows up completely. Screen shows up half then 3/4 and so on...

Would be helpful if you would offer a final version of 1.1 (or other older working releases) as .deb download and not with all code...)

I found a 1.1 deb and will now downgrade again until 1.2 is final and working

Regards,
Uli

how can I send pictures?

**Comment by rpetrich** [comment]
Do you by any chance have rounded corners enabled?

Downgrading is supported by removing the beta repository, uninstalling, then reinstalling via the public BigBoss source.

**Comment by Rainman99** [comment]
Yes, rounded corners are enabled
i'll send you pictures via twitter [PROSWITCHER]

**Comment by rpetrich** [comment]
How does alpha 2 fare?

**Comment by Rainman99** [comment]
Hi Ryan,
Alpha 2 works fine.
No freezing springboard, no more flickering, rounded corners are back. Seems to be faster than 1.1

only annoying thing is welcome message after each respring
regards, Uli

**Comment by rpetrich** [comment]
Excellent. I'll mark this as closed then.
