### ISSUE TITLE
After screen unlock screen is unresponsive

### ISSUE THREAD

**Issue by Vinski** [rpetrich/ProSwitcher#284]
After 1.2 a1 update: Always returning to home screen from unlock, or from application, screen becomes unresponsive. The fix is to launch and exit pro switcher.

To reproduce:
1. Have pro switcher 1.2 a1 installed
2. Wake phone from sleep and unlock the screen
3. Try exploring home screen or opening apps. They shouldn't be working.
4. Launch and exit Pro Switcher, touch in home screen is working again.

**Comment by ghost** [comment]
I also have this issue. After activating and exiting ProSwitcher it's fine until coming back to the Springboard from an app or after unlocking.

**Comment by daytonlowell** [comment]
A friend of mine had this same issue.  We though maybe it was another app like Winterboard or LastApp interfering, but removing those seemed to have no effect.  Also, only the main screen of apps was unresponsive, apps in the dock could still be interacted with.

**Comment by daytonlowell** [comment]
This is probably the same as issue 275.

**Comment by daytonlowell** [comment]
..and 274

**Comment by daytonlowell** [comment]
Think it only happens if you have no app running at all it locks the springboard.  Was able to reproduce on my iPad.

**Comment by daytonlowell** [comment]
So, steps to reproduce:
1. open proswitcher and kill all running apps
2. launch an app
3. go back to the home screen without backgrounding the app
4. try to interact with springboard
5. only thing you can interact with is the dock.

**Comment by wHack** [comment]
Actually it only happens if there are no cards to display. So you need to close all apps and change the settings to not display the springboard apps or the default apps.

**Comment by daytonlowell** [comment]
Makes sense.  I think the setting to show the springboard card is off by default.

**Comment by Maybewehitamoose** [comment]
Still, I'd prefer not to have an extra card for the springboard. Closing springboard card to respiring is amusing though.

**Comment by rpetrich** [comment]
Thanks for the detailed reports and discussion; they've helped. I've determined the source of the bug and it will be fixed in the next alpha
