### ISSUE TITLE
Springboard freezes after unlock

### ISSUE THREAD

**Issue by rockettpunk** [rpetrich/ProSwitcher#285]
After unlocking springboard is 'frozen' (ie, no scrolling or touch), however all the hardware buttons work and other programs (infinidock, qtweeter etc) are still responsive.
I have disabled proswitcher in sbsettings and this stops the problem.

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha 2

**Comment by rockettpunk** [comment]
The latest Alpha- the one released today / yesterday seems to have sorted it too.
