### ISSUE TITLE
re-arranging dock icons with PS open pushes dock to back

### ISSUE THREAD

**Issue by sysrage** [rpetrich/ProSwitcher#29]
If you tap and hold on a dock icon when PS is open, it starts the wiggle so you can re-arrange them but it moves the dock to the background so you then can't tap on any of the icons.

**Comment by grp** [comment]
Good bug!

**Comment by Surenix** [comment]
I found this a few days ago too

**Comment by rpetrich** [comment]
Simple solution is to force ProSwitcher to quit when edit mode is entered.
Implemented in unstable and on-track for 0.7 :)

**Comment by grp** [comment]
Best solution imo.
