### ISSUE TITLE
iPad - exit from apps

### ISSUE THREAD

**Issue by Sveat** [rpetrich/ProSwitcher#290]
When I exit from apps many times I can't open another app. To open another app first I need to push home button to open proswitch screen and only after I can open new apps.
Thanks

**Comment by Scuzzlebud** [comment]
I can confirm that on iPad. This is quite annoying. Just after you left an app (without backgrounding), you even can't flick through home screens. Only after activating PS again it works again.

**Comment by rpetrich** [comment]
Committed a fix to HEAD. Will be released in 1.2a2.
