### ISSUE TITLE
Psw alpha - rounded corners not working + graphic glitch

### ISSUE THREAD

**Issue by ghost** [rpetrich/ProSwitcher#292]
Hi,

I updated to the alpha to help test. For me, I updated, and found rounded corners no longer work and also appears to be a random graphic glitch... It sometime flickers, or "loses" half the card, the dock text vanishes (on the card not the actual dock)

j

**Comment by rpetrich** [comment]
We rewrote the rounded corner bits to use less memory and be slightly more GPU-efficient (helps especially on iPad)

Can you send a screenshot? Also, OS/hardware details would really help.

**Comment by ghost** [comment]
I have an iPhone 3GS, Jailbroken, 3.1.2.  I was going to upload the vid I took with displayrecorder, but alpha 2 was out when i checked cydia -- rounded corners are now fixed for me, and I havent noticed graphics glitch yet.  Let me know if you'd still like to see the vid.

J

**Comment by rpetrich** [comment]
Nope, looks like we're all good. I'll close this one.
