### ISSUE TITLE
ProSwitcher HD causes the screen to become unresponsive 

### ISSUE THREAD

**Issue by sturmen** [rpetrich/ProSwitcher#295]
iPad 3.2
ProSwitcher 1.2~alpha
Sometimes, when returning to SpringBoard normally (press of home button, no backgrounding involved), SpringBoard and the touchscreen as a whole, it seems, become unresponsive. I have exited this state by pulling up ProSwitcher and exiting it, and it works again.

**Comment by rpetrich** [comment]
Duplicate. Also, fixed in next alpha.
