### ISSUE TITLE
double press home button closes the active application and does not show proswitcher

### ISSUE THREAD

**Issue by knoopx** [rpetrich/ProSwitcher#296]
it seems like activator is not intercepting the double press event when an application is on the foreground. however it works in home screen. activator is configured to show proswitcher when double pressing home button "anywhere" on ipad.

**Comment by knoopx** [comment]
i tried resetting activator defaults and reconfiguring again. still not working.

**Comment by rpetrich** [comment]
Activator bug: pressing the home button performs the standard action _and_ closes the active application. Will look into this

**Comment by Bootrix** [comment]
Can verify same problem, I actually made an account to report this.  Thanks for looking into it!

**Comment by Chairos** [comment]
Same problem, funny thing it worked after installing, the other day it didn't. After downloading imobilecinema backgrouder was reconfigured to hold homebutton and ProSwitcher showed the issue described above.

**Comment by knoopx** [comment]
i'm using imobilecinema too, maybe its the reason

**Comment by brute** [comment]
I can confirm this problem too, just closes the app instead of activating pro switcher. Not using imobilecinema.

**Comment by thiswillnotdo** [comment]
*Bump ~ I'm so happy to have stumbled across this alpha release! Besides the bug where activating Proswitcher doesn't background the currently running app, it has been running flawlessly for me.

**Comment by darkytoothpaste** [comment]
I tried to circumvent the problem by docking ProSwitcher into SBSettings and try to run ProSwitcher while in another app. It simply returns to the home screen, then tried to run ProSwitcher but doesn't actually launch (i.e., does not display the running apps). So looks like the only way right now is to return to the home screen first then activate the switcher.
