### ISSUE TITLE
Bug when no program is open

### ISSUE THREAD

**Issue by helderlima** [rpetrich/ProSwitcher#299]
I have just discovered an annoying bug:
1- Close all the background programs that are open;
2- Lock the screen by clicking on the top button of the iPad;
3- Unlock the screen;
4- the dashboard is locked and you can not click on any icon;
After a long research, I have discovered that the problem is that a fully transparent layer of Proswitcher is on top of the dashboard on such situation. So, if you have enabled the dock on the pro switcher, only the dock will work.
In order to close the 100% transparent pro switcher, I click on the home button continuously, so the normal semitransparent dark background will open and I click on it to close the Proswitcher.

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha 2
