### ISSUE TITLE
No Screenshot, App Icon, or App Name

### ISSUE THREAD

**Issue by dharris** [rpetrich/ProSwitcher#30]
Sorry, i think i posted this twice but here is the correct place.

I have tried every other app I own and SlingPlayer is the only one with a bug. When you background SlingPlayer (either when its on just a setup screen or when its streaming video) and pull up ProSwitcher, there is no screenshot, app icon, or app name but there is a springdot showing you a backgrounded app which is the SlingPlayer. Its transparent and cannot be clicked on. You can see an "X" for the card on the very top of the screen.

Not sure why its just this app but I tried to confirm with other peeps but seems not many people have this app.

**Comment by mvit** [comment]
WinterBoard, CyCorder and ToggleSSH wont show either, thanks to Venomjojo for finding this, on an iPhone 3G

**Comment by dharris** [comment]
as an fyi, winterboard shows fine for me.  on a 3gs

**Comment by jerryen** [comment]
WinterBoard only shows the first time you background it. If you close it and background it again, it won't show. Not sure about the other apps.

**Comment by rpetrich** [comment]
Are all of you that have this bug on iPhone 3G's? Seems like it could be a bug in the code that handles low memory warnings.

**Comment by jerryen** [comment]
I'm on a 3GS and the latest unstable build doesn't fix it if that's what you thought it was.

**Comment by rpetrich** [comment]
SaiZn: if you comment out the contents of -[PSWApplication writeSnapshotToDisk] does it still occur?

**Comment by jerryen** [comment]
It doesn't occur if you turn off Show Default Apps and comment out the contents of -[PSWApplication writeSnapshotToDisk].

**Comment by dharris** [comment]
Not sure if it helps but on Slingplayer, i can take a screenshot no problem. If i then go right into proswitcher and background, same issue. On a 3GS.

**Comment by grp** [comment]
I can post a screenshot.

**Comment by rpetrich** [comment]
chpwn: if you can post a screenshot then you can also reproduce and fix it :P

**Comment by grp** [comment]
I can reproduce but not fix rpetrich.

**Comment by rpetrich** [comment]
ah, can you narrow it down then... I'm having trouble getting it at all

**Comment by grp** [comment]
It happens with Music Controls backgrounded apps as well as apps without a Default.png from my incomplete testing.

**Comment by ghost** [comment]
For me I just get a dot with no screenshot of the app, no close button, no name and no icon. All I see is the faded out Springboard screen with any other cards to the left and right of it and the dock visible at the bottom.

Everything still works except I can't click on the missing app.

You can try Storm 8's World War game, it seems to happen with that game.

Also if you close another app in the switcher then the missing app mysteriously appears with screenshot and all.

**Comment by ckong** [comment]
This sounds like the same issue I posted in the other thread "Show Default Apps and 3rd party apps".  I have a 3Gs.

**Comment by joneeboi** [comment]
If I swipe the rightmost (or leftmost) app to the left (or right), the name, dot and x button disappear from that app. If I swipe back to another app that's currently open, the trio come back. If I swipe back to the original rightmost app, the trio returns again. I just updated to whatever the newest version is as of Dec. 22.

**Comment by grp** [comment]
Fixed in unstable branch.
