### ISSUE TITLE
Whole Screen Freezes

### ISSUE THREAD

**Issue by sebastienpage** [rpetrich/ProSwitcher#300]
This issue happened the first time I installed PS. The whole screen froze. I was able to flick through pages of applications but I couldn't select any application. Nothing. I was also able to go to Spotlight search and type something but again, I couldn't TAP to launch anything.

I rebooted the iPad and the same issue came back. I simply clicked the OFF button once to "lock" my iPad. I then clicked on the home button and instead of using "Slide to unlock", I launched an app directly from the lockscreen via the SmartScreen app launcher. It worked fine after that.

Tonight, after several hours of use without any issue, the same problem reappeared. I used the same "technique" to get it to work again.

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha 2
