### ISSUE TITLE
shut down the override apps, touch is dead, must restart springboard, & report-bug page appear every restart

### ISSUE THREAD

**Issue by sylor** [rpetrich/ProSwitcher#301]
when shut down the override apps in the proswitcher(musice), touch is dead, must restart springboard, then it works. 
and the other one is everytime restart springborad,the proswitch report-bug page will appear....i dont know whats wrong  waitin for the new proswcher

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha 2

**Comment by sylor** [comment]
so great! ~~~ proswitcher is the best ~~  ：：）
