### ISSUE TITLE
Can't scroll horizontally or vertically

### ISSUE THREAD

**Issue by ghost** [rpetrich/ProSwitcher#308]
I've just updated to 1.2 alpha 1 today and now when my phone goes to sleep & I unlock it, I am unable to scroll the springboard in either direction. I'm also unable to open an app which is displayed on the screen until I respring.

Each time I need to open SBSettings and respring, then I am shown the bug popup message too.

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha 2 release.
