### ISSUE TITLE
Option to hide SpringBoard icon

### ISSUE THREAD

**Issue by likwidfuzion** [rpetrich/ProSwitcher#31]
Have an option like OverBoard to hide the ProSwitcher icon on SB.

**Comment by dharris** [comment]
You can do that now in SBSsettings with libhide.

**Comment by likwidfuzion** [comment]
I don't want to rely on libhide.

**Comment by grp** [comment]
Why? Works fine. No reason not to.

**Comment by rpetrich** [comment]
Not sure if I'm going to port in the OverBoard code for this; it's rather nasty
