### ISSUE TITLE
Apps Keeps Crashing

### ISSUE THREAD

**Issue by KayzeMSC** [rpetrich/ProSwitcher#310]
Helo,
Every since I have installed ProSwitcher on my iPad, I have noticed that apps are beginning to crash very frequently.

Thanks You,
Kayze

**Comment by rpetrich** [comment]
Crash or run out of memory? The iPad only has 256MB of memory and a screen that has 5X as many pixels as an iPhone 3G S. A lot of the optimization for ProSwitcher's iPad update has been convincing things to use less memory.

**Comment by ApolElmido** [comment]
Happens to me too. BiteSMS always crash on my iPhone 3gs.
