### ISSUE TITLE
Unable To Click Apps/Swide Scrssn

### ISSUE THREAD

**Issue by KayzeMSC** [rpetrich/ProSwitcher#311]
Hello,
Once I downloaded ProSwitcher on my iPad I have realized that whenever I hit the home button and go to the home screen, that I cannot click on any application that is not on the dock, I also cannot swipe the screen left or right and can only move the home screen by pressing the home button to go to spot light. 
I found out the way to fix this bug os by activating ProSwitcher when your iPad "freezes". However, this problem occurs every time I go to the homescreen or unlock the device.

Thank You,
Kayze

P.S I also noticed that sometimes I cannot click the home button while in an application.

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha 2
