### ISSUE TITLE
After login desk unresponsive

### ISSUE THREAD

**Issue by Gucky17** [rpetrich/ProSwitcher#312]
On an iPad bought in Germany, when I log in to the iPad from the slider screen. The desk is unresponsive meaning I can't click any app or slide to the next screen. If I activate proswitcher once by holding the home button and it shows no app running everything goes to normal. This is a really annoying bug. Otherwise a nice app. Thanks for the creation. 
This bug has been tested on two ipads, one wifi and one 3G. 
Thanks for the help.
Gucky

**Comment by rpetrich** [comment]
Will be fixed in the upcoming alpha 2 release
