### ISSUE TITLE
Unable to switch between hone screens after installing 1.2 alpha

### ISSUE THREAD

**Issue by AndyMDoyle** [rpetrich/ProSwitcher#313]
Installed 1.2 alpha (no other updates) and after the cydia respring Im unable to move between home screens or select and application on the main home screen about the dock icons. My only options are to run SBSettings, apps located in the dock, or power off.

Luckily I could access this page to report the bug because the Alpha message comes up after every respring.

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha 2.
