### ISSUE TITLE
Cards flickering

### ISSUE THREAD

**Issue by parmenti** [rpetrich/ProSwitcher#316]
The card images flicker in and out when navigating them..  sometimes to a box a quarter of size.  And bottoms strangely show more or less when zoomed or not zoomed. Used to be very fluent thumbnails..  not anymore.

**Comment by rpetrich** [comment]
Do you have the rounded corners option enabled by any chance?

**Comment by parmenti** [comment]
hi.. yes.. I do have it enabled..   does disabling it currently fix the problem until alpha 2?  Is that currently the problem?

**Comment by parmenti** [comment]
I noticed this myself..
if you background a new application then all the cards will flicker.. but if you close proswitcher card view and then relaunch cards.. then they stop flickering.. until you background a new application again.. then you'll have to leave card view and come back again.. and then they will look good again.  Seems to work that way every time.

**Comment by parmenti** [comment]
and yes.. it seems you're right.. everything seems to work fine if I turn of rounded corners.

**Comment by rpetrich** [comment]
Rounded corners have been fixed on non-iPad hardware in 1.2 alpha 2. Upgrade :)
