### ISSUE TITLE
iPod touch nonresponsive

### ISSUE THREAD

**Issue by Jbhotnessmon** [rpetrich/ProSwitcher#320]
When I go to the home screen from an app the touch screen becomes unresponsive execept for the dock apps. Also when I restart the springboard it immeditly says there is a bug with the program and takes me to this site.

PLEASE HELP

**Comment by Jbhotnessmon** [comment]
Btw I have an iPod 2g 16gb running 3.1.2

**Comment by rpetrich** [comment]
Fixed in the upcoming alpha 2
