### ISSUE TITLE
iPad touch screen freeze until relaunch

### ISSUE THREAD

**Issue by mbac** [rpetrich/ProSwitcher#323]
Hi,

Ever since installing Pro alpha on my iPad, I've been experiencing Springboard freezes whereby there's no response to touch, at all: no scroll nor launching other apps. The only solution is to either reboot device or, if Proswitcher is set to home button activation, to activate it and immediately close it.

As far as I can tell, this happens often as I quit an application, and every single time an app crashes to Springboard.

I wouldn't know what other info to report, but I'm more than willing to help fixing the problem.

**Comment by rpetrich** [comment]
Fixed in alpha 1.2 alpha 2
