### ISSUE TITLE
Reboot turns iPad into iPhone

### ISSUE THREAD

**Issue by neilio** [rpetrich/ProSwitcher#331]
Not sure what the specific technical description for this issue is, but the basic gist of it is rebooting the iPad after installing ProSwitcher often (most times) switches Springboard (?) into the iPhone's springboard - the unlock screen is broken, and the dock and # of icons visible change to match the iPhone.

Uninstalling Proswitcher seems to fix the problem.

**Comment by bibbillo** [comment]
I have the same issue, tough just uninstalling proswitcher doesn't solve the problem, i find it's still here until i remove activator, so i think there's the problem. I'm using Activator 1.4.0-beta2 and ProSwitcher 1.2-alpha-3

**Comment by wizard3m** [comment]
I´m having the same problem, but it only started after I updated backgrounder on July 1st.

**Comment by wizard3m** [comment]
Latest activator update solved it for me.

**Comment by bibbillo** [comment]
Fixed for me too with last activator release, i think you can close this :)

**Comment by Eatonfl** [comment]
On my ipad it was winterboard that caused it. I don't even have it on anymore since there are no icon themes for ipad yet.
