### ISSUE TITLE
Placing ProSwitcherBackground.png in Springboard folder does nothing on ipad

### ISSUE THREAD

**Issue by jessthecatmeow** [rpetrich/ProSwitcher#332]
When I place a PNG in /System/Library/CoreServices/Springboard.app and set the option to theme, the image does not show up as background. I've checked the preference loader plist and the preference plist and they reflect the change (I know the preference loader plist doesn't change, but I was just checking for the key). It doesn't crash or anything, but it does not actually display the image. A respiring and reboot did nothing as well. I have the latest release (alpha) for iPad.

**Comment by grp** [comment]
that's the wrong place to put it, it goes in ProSwitcher.app
