### ISSUE TITLE
Closing springboard will respiring the iPad.

### ISSUE THREAD

**Issue by ghost** [rpetrich/ProSwitcher#337]
In the settings for pro switcher HD, I turned on show springboard card. But, a couple of minutes ago, I accidentally swiped up on the springboard card and my iPad resprang. This isn't a very big thing, but I was wondering if you could put a notice somewhere so people know that you could respiring the iPad if they needed to in ProSwitcher. Also, people might be doing something when they respring, and they might lose their data... 
- Thanks, Conor

**Comment by grp** [comment]
As designed.
