### ISSUE TITLE
two proswitcher icon on iPod control

### ISSUE THREAD

**Issue by tonyli9323** [rpetrich/ProSwitcher#338]
So usually when I double hit my home button for my iPhone, proswitcher shows up just fine. But when I am using iPod, it will shows the ipod control and have three icons (close, iPod, and Proswitcher). After the upgrade, there are now 2 proswitcher icons (so it goes close, iPod, pro, and pro). The third icon doesn't work but the forth one does.

**Comment by grp** [comment]
not our bug
