### ISSUE TITLE
disable startup popup

### ISSUE THREAD

**Issue by numatod** [rpetrich/ProSwitcher#342]
I love Proswitcher till beginning, but till alpha release I have a wellcome popup each time I reboot or respring my iPhone!
Please, how to disable this?

**Comment by grp** [comment]
a) You opened this issue twice.
b) It's an alpha. It's not ready for public consumption, it's available for /testing/. Thus, having a warning that it isn't complete is perfectly valid. Please do not use unreleased software if you expect it to always work correctly; this warning is to remind you about that.

**Comment by numatod** [comment]
a) I'm so sorry, I wasn't able to find the issue that I just opened, thinking of a mistake so I tried again, apologize...
b) Ok, ok! I understand that perfectly, was just asking if there is a way to disable.Not this site purpose?
No matter, I will wait for public realise.
Whatever, good job.

**Comment by numatod** [comment]
thanks
