### ISSUE TITLE
nag screen PLEASE!

### ISSUE THREAD

**Issue by 3goldens** [rpetrich/ProSwitcher#347]
I'm really really tired of having to deal with this nag screen every single time this iPad resprings!  this has been in a state of beta for months now and if you don't at least give us an option to turn it off, make it an alpha program, or put it up for sale without this extremely annoying screen, I am going to use something else. its time man, move on, let us have the freedom to not have to deal with this idiotic reminder every time we have to do an update.

**Comment by grp** [comment]
Same as the other issue: this is an alpha. It will be gone in the final. If you don't want the nag screen, wait for the final release.

**Comment by 3goldens** [comment]
fuck you then asshole.
im not the only one who is tired of waiting on your slow lard assed final.
your program sucks anyway.
