### ISSUE TITLE
nag screen

### ISSUE THREAD

**Issue by 3goldens** [rpetrich/ProSwitcher#348]
here again, not two minutes later and after yet another update I have to see this annoying reminder.

**Comment by grp** [comment]
It's an alpha. Don't use it if you don't like it, and wiat for the final release.

**Comment by 3goldens** [comment]
its been in alpha far fucking too long you stupid fucking idiot!

grow up and release it.

**Comment by 3goldens** [comment]
I am going to send in a report every fucking time i see that fucking screen lard ass!

**Comment by grp** [comment]
There's nothing preventing you from finishing it yourself. We do this for free, you are owed nothing.

**Comment by 3goldens** [comment]
and again you could easily update the thing
AND include a check box to eliminate the nag once we know what to do.
NO ONE ELSE DOES THIS, FREE OR NOT, You just like the fact that people are reminded of this every god dam time they have to respring,
Your just being lazy and sitting back and doing nothing.
