### ISSUE TITLE
Proswitcher does not work together with 4.0.1 firmware

### ISSUE THREAD

**Issue by Thedarkspirit** [rpetrich/ProSwitcher#349]
I have a iPhone 3gs 16gb where I use to use proswitcher every day back when I had firmware 3.1.3  I was stupid enough to try and recharge on a different pc and it updated my fucking firm ware . I waited a long time fore a jailbreak fore the 4.0.0 but I finally found one fore firmware 4.0.1.. And baby I was back in business. ...... First installed cydia ofc then rock then proswitcher then it respringed in safe mode programs are installed but does not work at all. fucked up and does not help to disable or just uninstall it still starts insafe mode with out a way to get out of it. Tryed this 3 times and tryed backgrounder alone no problem there. Plz fix fast I love the program it is the only thing that makes this phone way better than htc android

**Comment by grp** [comment]
Apple's multitasking is better. Use it.

**Comment by Thedarkspirit** [comment]
Well it does not work with you tube 4 an eksampel cant lisson to New numbers and be on the net at the same time
