### ISSUE TITLE
No statusbars in the card

### ISSUE THREAD

**Issue by 3744111** [rpetrich/ProSwitcher#35]
It seems that the statusbar on the cards somtimes isnt there
and other times it is. It also mostly happens for certain apps.
It mostly happens to the phone card and preferences.

**Comment by GabsNL** [comment]
Yes, I've had the same issue. IMO it would be better to auto 'cut out' the statusbar out of all the card images (Like Palm Pre) because it also shows the time and makes it look really fake-ish.

**Comment by rpetrich** [comment]
Agreed, statusbar should be removed from all images... now we have to find a decent way of doing that (perhaps by offsetting into the buffer when portrait and doing some funky stride math when landscape)

**Comment by grp** [comment]
eh or just mask off the top 20px and store a bool if it was showing when it exited

**Comment by rpetrich** [comment]
messing with the buffer to perform cropping is actually quite easy and _very_ cheap, just have to perform pointer math properly :)

**Comment by grp** [comment]
Yeah; remnids me of when I was fucking around with TPL formats...those were the most annoying thing EVER.

**Comment by GabsNL** [comment]
If you mask off only the top 20px wouldn't that cause problems with landscape apps?

**Comment by grp** [comment]
Oh, yeah, good point.

**Comment by rpetrich** [comment]
This will definitely have to wait for the next beta

**Comment by n00neimp0rtant** [comment]
Looking forward to a fix for this, thanks guys

**Comment by Mike11** [comment]
I guess I'm alone with this one, but I like the fact that I can see when I last used an app via the statusbar. Maybe an option if it's not too much work.

**Comment by sstarr07** [comment]
Thanks for this fix!

**Comment by rpetrich** [comment]
Mike11: will have to be a hidden option.

**Comment by GabsNL** [comment]
Yes, thanks for the fix in 0.8
