### ISSUE TITLE
HOW TO FINALLY REMOVE THE PROSWITCHER ALPHA POPUP AFTER REBOOT!!!!

### ISSUE THREAD

**Issue by Mikejd1** [rpetrich/ProSwitcher#350]
I figured it out.   Open iFile on your jail broken iPad. Go to the root directory and search for Proswitcher (under hierarchy). 

Open proswitcher.dylib with text viewer, edit it and remove the following line

"superview

**Comment by grp** [comment]
This is an Alpha. If you are using it, you should know that. It's not meant for general usage, only for testing. Closed.
