### ISSUE TITLE
Pandora w/ MusicControls

### ISSUE THREAD

**Issue by 3744111** [rpetrich/ProSwitcher#36]
Pandora doesn't quit properly with music controls installed

http://img43.imageshack.us/img43/4167/87753804.jpg

**Comment by dharris** [comment]
Doesnt happen to me. Do you have latest pandora installed? On a 3G or 3GS? Were you in the middle of playing a song? I test playing a song and just scrolling through interface. Quit no problem both with the "X" and sliding card up.

**Comment by grp** [comment]
I've had a similar bug, but not with pandora or music controls.

**Comment by rpetrich** [comment]
MusicControls has it's own built-in backgrounding that suppresses deactivate killing the process; we will have to contact phoenix3200 for details on how to suppress that (similar to -[SpringBoard setBackgroundingEnabled:forDisplayIdentifier:])
