### ISSUE TITLE
Install ProSwitcher Error

### ISSUE THREAD

**Issue by bjmax80** [rpetrich/ProSwitcher#362]
When attempting to install ProSwitcher 1.2-alpha-3 on my 3Gs 4.0 I receive this message: Note: The requested mod cannon be applied due to required dependencies or conflicts that cannot be automatically found of fixed. 
Modifications
Install ProSwitcher
Remove libxml2 Library. SQLite 3.x Library. SwitcherMod  

I have removed each of these and when I do it tells me to remove my iPhone firmware and to install backgrounder and Activator, I install backgrounder and proswitcher and then it tells me to remove those programs listed above, again. 

Is my firmware too new? it just gave me this message: iPhone Firmware>= 4.0 this is the first time in numerous attempts to get Palm Pre Multitasking working on my phone.

Thanks for any feedback or help you can give me. Also if 4.0 is too new then when do you anticipate an update that will allow it to run on 4.0?

**Comment by grp** [comment]
ProSwitcher doesn't support 4.0, it conflicts with a firmware greater than or equal to 4.0.
