### ISSUE TITLE
On reboot or springboard relaunch I get a "submit bug report" prompt.

### ISSUE THREAD

**Issue by ccarver** [rpetrich/ProSwitcher#365]
If I reload my iPad or relaunch the Springboard I get a popup giving a quote and a choice to submit a bug report, looking along the lines of:

"Quote about programming"
Please submit bug reports
  (Cancel)   (Submit Bug)

It's annoying if you turn your iPad on and off frequently, hopefully it's an easy fix.

**Comment by ccarver** [comment]
Never mind, I read another thread about how to fix it.

**Comment by grp** [comment]
It's an alpha, any usage of it should be for testing, so this notice is appropriate to remind you of that. Any "fix" for this is not approved and likely dangerous.

Please do not use ProSwitcher on an iPad for anything except testing, and please do not use unofficial versions.

**Comment by ccarver** [comment]
Ok, is the official release coming out soon?

**Comment by grp** [comment]
Probably not; nobody is developing it currently.

**Comment by ccarver** [comment]
Hmm, well what do you think I just do about the popup? Just live with it?

**Comment by grp** [comment]
It's a testing version. If you aren't testing it, then it shouldn't be installed.

**Comment by ccarver** [comment]
Okay, thanks.
