### ISSUE TITLE
Springboard dead when iPad start up

### ISSUE THREAD

**Issue by futurist** [rpetrich/ProSwitcher#371]
Springboard dead when iPad start up, and there are no icons, only wallpaper, Waiting for a long time, spring board will auto restart, app icons appear. IOs 3.2, jailbreaked. Email is jamesyang@gmail.com

**Comment by grp** [comment]
I experience this issue (with OverBoard) every time I press the home button, but I can fix it by pressing the home button again when at the blank screen.

Is this an OverBoard bug?
