### ISSUE TITLE
Adding Corner Radius causes extreme PS lag.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#38]
[ProSwitcher 0.6]
If you invoke Corner Radius to Small or Large on an iPhone 3G it causes extreme slow downs in ProSwitcher. Even on an iPod 3G(eneration) it slows it down by a bit.

**Comment by grp** [comment]
Not our bug, go blame apple for not allowing the GPU to do corner rounding and forcing it on the CPU. We do this in the best way we can!

**Comment by rpetrich** [comment]
Latest uses a mask instead; this appears to be faster, but I don't have an old device to test on

**Comment by GabsNL** [comment]
If you include the fix it in the next beta release (0.7) it can be tested.

**Comment by rpetrich** [comment]
unstable becomes master when we decide it's stable enough :P

**Comment by GabsNL** [comment]
Haha, alright, put it in beta when you think it's stable enough :)

**Comment by rpetrich** [comment]
v0.7 and v0.7.2 have this code; they should be speedier than 0.6
