### ISSUE TITLE
Turning off Page Dots does not work.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#39]
[ProSwitcher 0.6]
In Settings.app when you turn off Page Dots it does not work.
You still see the (app) page dots.

**Comment by sysrage** [comment]
Dupe: http://github.com/rpetrich/ProSwitcher/issues#issue/33

**Comment by GabsNL** [comment]
Yes, sorry, I just noticed. Can I delete my issue?

**Comment by grp** [comment]
Just fixed.
