### ISSUE TITLE
Tethering 'status bar' cuts off top of ProSwitcher windows

### ISSUE THREAD

**Issue by sysrage** [rpetrich/ProSwitcher#40]
If the tethering bar is showing and you have the dock and app titles showing, the top of windows in ProSwitcher are cut off (including the X to close button). I'm assuming the same would be true during a phone call. Not really a bug, I guess. Something to consider, though. Maybe, if possible, squish things down a bit more if tethering is enabled or the user is on a phone call.

**Comment by rpetrich** [comment]
Good catch. Also happens when Voice Memos recording is active

Fixed in unstable; will be in ProSwitcher 0.7

**Comment by sysrage** [comment]
Voice recorder status bar still cuts the top of cards off in 0.7.3. Not at home so can't test with tethering one, but I assume they would all behave the same.

**Comment by rpetrich** [comment]
Screenshot?

Also, it only adjusts when you activate ProSwitcher and won't change layout if you enable tethering from my SBSettings toggle while ProSwitcher is active (this is a bug, but is so small it's not worth fixing)

**Comment by sysrage** [comment]
Well it's not happening anymore in 0.75.. It was in 0.73 :P

**Comment by rpetrich** [comment]
Ah, cool
