### ISSUE TITLE
status bar doesn't open

### ISSUE THREAD

**Issue by xXFR0STBYTEXx** [rpetrich/ProSwitcher#41]
i have tap, slide down, left, right all checked and tried it and doesn't open it. I'm guessing it doesn't work because i have SBSettings installed as well.

**Comment by sysrage** [comment]
works just fine with sbsettings installed. you're trying them from the springboard, not within another app, right? doesn't work yet from within other apps.

**Comment by xXFR0STBYTEXx** [comment]
yes im trying it from the springboard

**Comment by grp** [comment]
libactivator bug.

**Comment by rpetrich** [comment]
SBSettings with the more sensitive swipe option steals touches. Marked as won't fix
