### ISSUE TITLE
Keyboard bug

### ISSUE THREAD

**Issue by sagitt** [rpetrich/ProSwitcher#43]
there is a bug if open proswitcher from spotlight or ever there is a keyboard

screenshot:

http://img22.imageshack.us/img22/2240/img0072p.png

**Comment by grp** [comment]
Yes, should be a simple fix, very valid bug :).

**Comment by sagitt** [comment]
I think is userful use kirikae method... On top ever!!!

If you are in app, if you are in springboard etc! Anyway if dock is enabled and we are in app dock stay hidden

**Comment by grp** [comment]
Bug fixed with one added line of code!

**Comment by sagitt** [comment]
well ^^
