### ISSUE TITLE
Using DoubleHome as activator + iPod Controls on LockScreen

### ISSUE THREAD

**Issue by ghost** [rpetrich/ProSwitcher#44]
I noticed today, that if i lock the screen, and use the doublehome to bring up iPod controls - this no longer works. if i then unlock, ProSwitcher is showing.  I guess the activation method is still calling ProSwitcher..... im thinking libactivator needs to be disabled at lockscreen :)

jtanner

**Comment by sysrage** [comment]
yep. just confirmed this. not only does ProSwitcher show after unlocking, but the dock is hidden behind the ProSwitcher screen. Probably a LibActivator issue to make it not work on lock screen, but the dock being in the background might be a sign of a ProSwitcher problem that will surface later.

**Comment by ghost** [comment]
woops, yeah i forget to mention the dock was covered!

I should perhaps also say, im using the Master source, compiled on my own machine, (with rpetrich's help) and libactivator 0.9 from cloudhub.github (rpetrich's).  I DONT have the prefloader 1.2b installed as im not a beta tester.

**Comment by grp** [comment]
libactivator bug -- not in ProSwitcher.

**Comment by rpetrich** [comment]
Not actually a libactivator bug. Some listeners may want to receive events while SpringBoard is locked, so libactivator has to dispatch them. I will commit a fix for ProSwitcher
