### ISSUE TITLE
Tap background to close

### ISSUE THREAD

**Issue by sagitt** [rpetrich/ProSwitcher#45]
1. Add an option to add a new default card: springboard card. (red (x) button... If the user swipe up or press (x) red, proswitcher done the respring - (x) as cydelete)
2. If user activate proswitcher from running app, proswitcher send the app in background, go to spring and open proswitcher card selector
3. If the user press on background (no card) of proswitcher selector, proswitcher will be close!

**Comment by rpetrich** [comment]
1. On the to do list, might not make it for 1.0
2. Yup, that's how we're doing it for next release
3. That's how it will be in next release (though only on the bottom 1/4 of the screen)

**Comment by grp** [comment]
1. should be a setting if implemented at all

**Comment by sysrage** [comment]
agreed with chpwn. I don't want an extra card cluttering things up :D

**Comment by rpetrich** [comment]
that is our philosophy. options, options and more options!

**Comment by grp** [comment]
1. should also be a setting!

**Comment by sagitt** [comment]
yes, the options!

**Comment by grp** [comment]
I just realized I looked like an idiot there: github was trasnlating my "3." to a "1." while posting.

**Comment by rpetrich** [comment]
lol. github flavored markdown tastes nasty :P

**Comment by rpetrich** [comment]
Only 1. is left to be implemented
(Also, this really should be three separate issues)

**Comment by sysrage** [comment]
lol.. #1 sure is getting a lot of attention :P

**Comment by grp** [comment]
All are completed and implemented, so this is now a triple-duplicate.

**Comment by sagitt** [comment]
why you don't use (X) red as safari or cydelete for springboard? classic apps with (x) will be closed... springboard respring!

**Comment by rpetrich** [comment]
sagitt: I don't think we have plans to implement that. anyway, this bug is closed and that would be a new request anyway.
