### ISSUE TITLE
In-app activation only works if it's the first activation of PS

### ISSUE THREAD

**Issue by jerryen** [rpetrich/ProSwitcher#46]
PS still activates if you activate it after the first time while in an app but it won't show.
I fixed it by changing lines 107-124 in PSWViewController.m to this:
            CALayer *layer = [snapshotPageView.scrollView layer];
            if (animated) {
                view.alpha = 0.0f;
                [layer setTransform:CATransform3DMakeScale(2.0f, 2.0f, 1.0f)];
                [UIView beginAnimations:nil context:nil];
                [UIView setAnimationDuration:0.5f];
                [UIView setAnimationDelegate:self];
                [UIView setAnimationDidStopSelector:@selector(didFinishActivate)];
                [layer setTransform:CATransform3DIdentity];
                [view setAlpha:1.0f];
                if (GetPreference(PSWShowPageControl, BOOL))
                    [pageControl setAlpha:0.0f];
                [UIView commitAnimations];
                isAnimating = YES;
            } else {
                [layer setTransform:CATransform3DIdentity];
                [view setAlpha:1.0f];
                if (GetPreference(PSWShowPageControl, BOOL))
                    [pageControl setAlpha:0.0f];
            }

(I'm a github newbie so I don't know how to commit stuff and what not.)

**Comment by rpetrich** [comment]
Which revision is this against? Head of stable?
If in doubt, commit to a fork and then send me a pull request :)

**Comment by jerryen** [comment]
unstable

**Comment by grp** [comment]
Pushed your fix to unstable
