### ISSUE TITLE
ProSwitcherBackground.png doesn't fill the entire screen.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#47]
[ProSwitcher 0.6]

If you place the ProSwitcherBackground.png inside /System/Library/Coreservices/SpringBoard.app and activate Background > Theme in Settings.app it doesn't fill up the entire background when activating ProSwitcher.

As seen in this screenshot I made: http://img10.imageshack.us/img10/2962/img0204z.png
The StatusBar and top part of my Dock are not included.

**Comment by rpetrich** [comment]
Unstable has a fix for this :)
