### ISSUE TITLE
While app is loading allows for ProSwitcher activation.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#48]
[ProSwitcher 0.6 + LibActivator 0.9.1]

If I open an app, say, Calcullator and quickly activate ProSwitcher by Doubble tap while the app is still loading it opens up PS and closes it right after the app has opened.

Screenshot: http://img51.imageshack.us/img51/3159/img0207.png

**Comment by rpetrich** [comment]
Looks like we need to detect when SpringBoard is in the activate/deactivate animation and abort...

**Comment by grp** [comment]
Or just disable activation when an icon is pressed and only enable it again when springboard is shown.
