### ISSUE TITLE
Kirikae-like Method to Enable Backgrounding for an Active Application

### ISSUE THREAD

**Issue by sturmen** [rpetrich/ProSwitcher#49]
If you invoke Kirikae while in an app and switch to SpringBoard, that app is automatically backgrounded. This essentially makes it so you don't have to press+hold a button to background something, freeing it up for something else.

**Comment by sturmen** [comment]
I can't get it to show up as a feature request.

**Comment by rpetrich** [comment]
Already added in the "unstable" branch
