### ISSUE TITLE
Ghosted Backgrounded App

### ISSUE THREAD

**Issue by WYSE** [rpetrich/ProSwitcher#5]
Hye guys i was messing around with it a bit yesterday and I closed mr iRealSMS and went back to ProSwitcher to see if it closed... i saw a ghosted image of it instead.

**Comment by grp** [comment]
What does ghosted mean?

**Comment by danzimm** [comment]
ive had this-the app is stuck on its closing cycle
u need to force quit the app then

**Comment by rpetrich** [comment]
Can you post a screenshot?

**Comment by dasherious** [comment]
had the same with accuweather 3gs 3.1.2

**Comment by dasherious** [comment]
opps http://img692.imageshack.us/img692/1828/photonk.jpg

**Comment by rpetrich** [comment]
Hmm... not sure how to classify this. The apps are still running because they're taking awhile to close, but the user has clearly requested that they be closed. What should the proper behaviour be here?

**Comment by grp** [comment]
I get this sometimes too when swiping up, it gets stuck for a second while it is closing.

**Comment by rpetrich** [comment]
Perhaps we should just remove the card even though the process is still alive? (I think SpringBoard will eventually kill zombies anyway)

**Comment by grp** [comment]
Maybe; this is an interesting issue.

**Comment by rpetrich** [comment]
Committed a fix to unstable; not sure if I 100% like this method though...
