### ISSUE TITLE
Ability to close Phone and Mail

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#52]
[ProSwitcher 0.6]

When trying to close Phone.app or Mail.app (with Push enabled) it does this weird fade animation and not closes the apps. I realize that Phone and Mail always run in the Background and normally cannot be closed but Kirikae has the abbility to close 'em. Perhaps you should take a look at the Kirikae code to see how to do it.

I often close them temporarily when I'm going to play a game and can't do this with ProSwitcher.

**Comment by rpetrich** [comment]
Will need more information; this works fine on my device. A list of installed MobileSubstrate/Rock Extensions would help.
(I've heard of this before, but haven't been able to reproduce it)

**Comment by GabsNL** [comment]
Installed MS extensions ATM: 
Yourtube
libactivator
PreferenceLoader
Backgrounder
ProSwitcher
- aditional info
  Push enaibled for one Gmail account (Exchange ActiveSync)
  Carrier: Vodofone NL
  Using Kirikae I can close Mail and Phone.

**Comment by rpetrich** [comment]
Wow, that's a really clean device. Clearly we're not doing something right here. Device/firmware specs?

**Comment by ejoya** [comment]
In proswitcher you can exit the app but it will return again. I think the threadstarter wants it to completely exit without automatically reloading. The new build of Kirikae can completely exit the phone and mail app but older builds does not.

**Comment by rpetrich** [comment]
On both chpwn's and my devices neither Phone nor Mail "return from the dead."

You say Kirikae had this issue in the past, but no longer has it? Perhaps we should examine the changelogs to see how it was solved...

**Comment by GabsNL** [comment]
ejoya is right. In the latest build of ProSwitcher [0.7.2] if I close mail or phone it closes the aoo > ProSwitcher quits without animation > the app reopens.

Note:
If I turn off Push I can close Mail.
If I turn on airplane mode I can turn off Phone.

**Comment by rpetrich** [comment]
Can anyone who has this post their firmware & device versions? (I'd like to do a comparison)

**Comment by ejoya** [comment]
@GabsNL same with you, turning on push mail will automatically load mail app again.
@rpetrich yes the newest kirikae release build can complete quit the app without reloading. But I'm not sure if it only works for 3.1.x.
iPhone 3G OS 3.1.2

**Comment by ejoya** [comment]
http://www.ipoday.net/update/ipodtouch_applications/item_3622.html check kirikae logs

**Comment by GabsNL** [comment]
I've got the same specs as ejoya.
iPhone 3G Running FW 3.1.2

**Comment by rpetrich** [comment]
This looks to be the commit:
http://code.google.com/p/iphone-kirikae/source/detail?r=120

**Comment by GabsNL** [comment]
Yes, I believe that was added in the latest build and fixed the Phone/Mail reopening.

**Comment by rpetrich** [comment]
Committed in unstable; will be in next release

**Comment by GabsNL** [comment]
Thank you, Ryan :)

**Comment by ejoya** [comment]
thanks

**Comment by danzimm** [comment]
is this in .7.3? 
doesnt work for me-phone keeps coming back

**Comment by GabsNL** [comment]
No, not fixed yet in 0.7.3
