### ISSUE TITLE
Themed Icons

### ISSUE THREAD

**Issue by biird** [rpetrich/ProSwitcher#53]
I've noticed that when I background apps like Beejive or any downloaded app, the Winterboard icon will show next to the the name. Stock apps (Mail, Phone, iPod) stay with the default icon. Just a heads up :)

**Comment by grp** [comment]
Its more of:
- Winterborad themes usually on theme the big icon
- If there is no small icon, it shrinks the big icon
- built in apps have a small icon, which isn't themed

That explains why this happens, and should we alwyas use the big icon scaled? its slower but it might be nicer :/

**Comment by biird** [comment]
Yeah- I think a lot of users are probably using themes so may as well give it a shot...hopefully it doesn't slow down too much! :)

**Comment by rpetrich** [comment]
We should be able to scale on GPU; for the number of icons we have, this should be fine.

(For OverBoard I have a really crazy caching scheme for the utmost speed)

**Comment by grp** [comment]
Yeah, sounds good.
