### ISSUE TITLE
libactivator 0.9.1 bugs.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#54]
[ProSwitcher 0.6 + libactivator 0.9.1]
Wasn't sure where to post the remaining libactivator 'Activation Methods' bugs so here are the ones I've found.

HomeButtonPressAtSpringBoard: doesn't work
SpringBoardIconPinch/Spread: works but if you keep your fingers on screen you can move SpringBoard icons.
HomeButtonDoublePress: works but destroys built in iPod Pop controls and Lockscreen Music controls.

One last thing is when libactivator is installed regardless of settings the one tap on homescreen to first page and one tap to spotlight don't work.

**Comment by biird** [comment]
HomeButtonPressAtSpringBoard works for me

**Comment by rpetrich** [comment]
Please revisit this after 0.7

**Comment by GabsNL** [comment]
[ProSwitcher 0.7.2 + libactivator 0.9.1]

HomeButtonPressAtSpringBoard: works, but you can't use in-app (maybe make one tap home button inside app also invoke in-app?)
SpringBoardIconPinch/Spread: works, fixed
HomeButtonDoublePress: works, controls are fixed

One tap to first page/spotlight is also fixed (except when using HomeButtonPressAtSpringBoard but that's expected behavior and not a bug.)

Thank you for the fixes :)

**Comment by rpetrich** [comment]
Alright, I'll close this then
