### ISSUE TITLE
Invoking Search While PS is open fails to exit PS

### ISSUE THREAD

**Issue by dharris** [rpetrich/ProSwitcher#56]
Not sure if its a "true" bug but if in proswitcher and enable search (so i use swipe down for PS and double tap home for search) cards show up over/in search. 

However, you can still type as the search bar is dimmed but active. You can also get rid of PS while in search without ever leaving it....

Nonetheless probably better for it to autoclose when search is invoked.

**Comment by rpetrich** [comment]
Fixed in unstable
