### ISSUE TITLE
Doesn't work right with Categories/CategoriesSB

### ISSUE THREAD

**Issue by ckong** [rpetrich/ProSwitcher#59]
After placing ProSwitcher in a Categories folder, tapping the PS icon crashes right to the SpringBoard.  

I also noticed that when adding PS to a Categories folder, the PS icon is a big question mark "?" instead of it's real icon.

I'm using Categories 2.29 with CategoriesSB 1.5.3, and PS 0.7 with LibActivator 0.9.1.

**Comment by grp** [comment]
Real bug, but not going to get solved soon.

**Comment by rpetrich** [comment]
Can you post a crash log from crash reporter?

**Comment by GabsNL** [comment]
Also noticed with when you open a Category with CategoriesSB and invoke ProSwitcher afterwards it opens up behind the Category.
SS: http://img706.imageshack.us/img706/9492/img0224.png

**Comment by rpetrich** [comment]
Oddly enough, I just fixed this for my internal OverBoard beta :P
Will add a fix to unstable

**Comment by ejoya** [comment]
using 0.72 and PS real icon is shown inside the categoriessb folder.

**Comment by ckong** [comment]
rpetrich: Glad to hear it's fixed in OverBoard.  Just for giggles, I ssh'd into my phone, and looked for a crash report, but was unable to find it.  Can you let me know how to get it?  (sorry for the noob question; I did a updatedb/locate and still couldn't find one)

ejoya: I just upgraded to PS 0.7.3.  Icon still a big question mark when choosing PS from the list.  PS also still crashes to the Springboard when placed into a folder.

**Comment by rpetrich** [comment]
Send crashes with Crash Reporter (as always)

**Comment by GabsNL** [comment]
As of ProSwitcher 0.7.3 it doesn't open up behing CategoriesSB anymore. So that's one issue fixed :)

**Comment by ckong** [comment]
rpetrich: I installed Crash Reporter 0.2d from Cydia, and retested PS 0.7.3 inside a folder.  PS dumped back to the Springboard, but Crash Reporter didn't report a problem.  Let me know if there's something else you want me to try.
