### ISSUE TITLE
Page Indicators Don't Appear Until First App Launch

### ISSUE THREAD

**Issue by DannyNemer** [rpetrich/ProSwitcher#61]
Up until you first launch an application on your device after a respring or reboot, ProSwitcher does not display the page indicators (page dots) beneath the application screenshots (cards). I have tried numerous settings configurations, and with each one, the issue persists.

Before launching an application (after a respring or reboot):
http://min.ie/2yS

ProSwitcher settings:
http://min.ie/2yR

After launching an application (in this case it was the Settings app):
http://min.ie/2yQ

Note: The page indicators will appear after you first launch any application, excluding the default applications that are already running and are visible in ProSwitcher.

**Comment by grp** [comment]
Note: the page dots are not displayed if there is only one running app.

**Comment by DannyNemer** [comment]
Actually, in the screenshots above, two apps are running: Phone and Mail. Sorry, I should have set for three cards to be visible to better show the bug. Screenshots are updated.

**Comment by rpetrich** [comment]
Hmm... interesting bug. chpwn, you want to handle this? (you seem to be having fun with UIPageControl :)

**Comment by grp** [comment]
I can't see at all why this is happening :P

**Comment by dharris** [comment]
Happened to me in 0.7 but not in 0.7.3. Works fine now.

**Comment by DannyNemer** [comment]
Updated to 0.7.3 and unfortunately I am still experiencing the same issue.

**Comment by rpetrich** [comment]
No update related to this was in 0.7.3 nor 0.7.2
