### ISSUE TITLE
Show Default Apps and 3rd party apps

### ISSUE THREAD

**Issue by ckong** [rpetrich/ProSwitcher#63]
If the Default Apps toggle is "on", 3rd party apps do not show an screen-shot in the ProSwitcher.  Turn this option off causes the app screen-shots to appear (so for now, I'm leaving it off).

I'm using PS 0.7 with LibActivator 0.9.1.

**Comment by rpetrich** [comment]
Can you post screenshots? Showing previews seems completely unrelated except in the case of memory-constrained environments. Can you also post your device/firmware information and total free memory?

**Comment by ckong** [comment]
I'd be glad to upload a screenshot.  Sorry but I'm a bit of a noob on this forum.  I don't see an upload link in the comments so I'm not sure how to upload an image.  :(  If you let me know, I'll post one.  (sorry!)

I'm running a 3GS w/ 32Gb.  I do have SBSettings installed and see that I'm running 121MB free with one 3rd party app running in the background.

I've just upgraded to PS 0.7.3.  It has the same problem.  A 3rd party app has a blank screenshoot.  Turning off Default Apps restores it to the PS screen.

**Comment by grp** [comment]
Just post the image on any other site.

**Comment by ckong** [comment]
Okay...  I've posted an image here:

http://www.freeimagehosting.net/image.php?bc6b54b540.png

It's interesting.  As I was trying to replicate this problem for this screenshot, I found that some 3rd party apps do work correctly with PS.  Others, like "Army Knife" (screenshot) or "HICalc" do not.

You can see that within PS, the app has no image, or a "close" button.  The first three running apps are my Phone, Mail, and iPod default apps.

**Comment by ckong** [comment]
I just upgraded to PS 0.7.5.  Looks like this update fixed the screenshot issue.  I have Default Apps turned on and ran HICalc in the background.  This time, there was a screenshot.

I'll report back if the problem reappears but it looks like it's fixed.

**Comment by grp** [comment]
K, closed.
