### ISSUE TITLE
overboard

### ISSUE THREAD

**Issue by warcopolo** [rpetrich/ProSwitcher#64]
1.after i install PS,overboard cant work by home tap 

but when i turn off "animated" in overboard setting,

overboard can work now...

---

2.when i use free memory ,iphone go to safe mode

then i try to open overboard by home tap(not in safe mode),but it doesnt work again

so i reboot,but still not work

so i open overboard in SpringBoard,after this,overboard can work again by home tap...

weird,i hope u know what i saying....

my poor english...sorry

**Comment by grp** [comment]
Just wait for the next overboard :).

**Comment by rpetrich** [comment]
Yup, OverBoard is getting a massive 1.1 update that should fix all of these.
