### ISSUE TITLE
Closing Mail or Phone Apps Exits ProSwitcher

### ISSUE THREAD

**Issue by DannyNemer** [rpetrich/ProSwitcher#67]
Whenever you exit the Mail or Phone apps via ProSwitcher, ProSwitcher instantly closes. I believe this happens because the Mail and Phone apps are meant to always be open and automatically reopen when killed. For this reason, it might be best that the ability to quit the Mail and Phone apps via ProSwitcher be removed, while keeping the ability to have the Mail and Phone apps appear in ProSwitcher.

**Comment by DannyNemer** [comment]
All the more info that I can give is this: Whenever you close either the Mail or Phone app from within ProSwitcher (either through taping the "x" in the corner or swiping upward), ProSwitcher instantly exits to the SpringBoard without taping the home button or anything (completely on its own). When you reactivate ProSwitcher, whichever of the two apps you just killed (either Mail or Phone) have been added to the rightmost card. I hope this helps :-)

**Comment by grp** [comment]
It works fine here.

**Comment by rpetrich** [comment]
Can you post device/firmware information and a list of packages you have installed? It seems as if Mail and Phone are relaunching and causing some havoc.

**Comment by dharris** [comment]
This happens to me too. I tried disabling all my MS add-ons but still happens. I am running 3gs 3.1.2. Running the following: Winterboard, FiveiRows, FiveIconDock, All the PS extensions, backgrounder, blanknull, categories and categoriesSB, iblank, pdanet, sbssettings, statusbardots, 3g enrestrictor.

**Comment by j4m1eb** [comment]
exact same issue for me. 3GS 3.1.2 running backgrounder kirikae sbsettings 3g unrestrictor, music controls, stack v3, terminal, CHPWN EDIT NO PIRACY PLEASE!. dont think its a massive issue, but was happening to the ipod too before a reboot. Having said that just tried kirakae and it happily quits mail and phone

**Comment by DannyNemer** [comment]
iPhone 3GS 3.1.2

Mobile Substrate Extensions:
ProSwitcher, LibActivator, & PreferenceLoader
Backgrounder
SBSettings, libhide, & RotationInhibitor (an SBSettings toggle)
WinterBoard
LockInfo, WeatherIcon, & ClockHide

**Comment by thelatinist** [comment]
I'm having the same issue.  I think it has something to do with those apps relaunching automatically.  When push email is disabled, Mail closes normally and does not close ProSwitcher.

3GS 32GB 3.1.2 (7D11), 05.11.07, JB w/PwnageTool, unlocked w/blacksn0w.

I have the following MobileSubstrate extensions installed:

attachment= for mailto:, Backgrounder, Categories, Cycript, CyDelete, Cydget, Cyntact, Five Icon Dock, iMobileCinema SBController, iPod Touch Dock, iPodPop, Kirikae, LEOBADGE, LibActivator, libhide, LiveClock, LockLight Cydget, Popup Blocker, PreferenceLoader, PrivaCy, ProSwitcher, ReflectiveDock, Rotation Inhibitor, Safari Download Manager, Safari Download Toggle, SBSettings Tethering Toggle, SBSettings, UserAgent Faker, WebViewController, WinterBoard, 3G Unrestrictor

I am assuming you don't want to know all the other packages I have installed.  If you do, let me know.

**Comment by DannyNemer** [comment]
I'm pretty sure this issue has not been addressed yet, but just for the sake that it is not ignored: This issue still exists in ProSwitcher 0.8

**Comment by sstarr07** [comment]
I too have this issue, but its only when I close the phone app, I know its not necessary to close the phone app but when I did, it closed PS and when activated again it had the phone app but it was a white gui

**Comment by sysrage** [comment]
Happens to me, too. 3GS 3.1.2 blackra1ned

**Comment by rpetrich** [comment]
Can someone with this bug get in IRC so I debug this?

**Comment by grp** [comment]
Do you all have push enabled?

**Comment by DannyNemer** [comment]
I have push enabled, but that wouldn't explain why this happens with the Phone app as well, would it?

**Comment by rpetrich** [comment]
chpwn: I have someone helping me debug; hopefully we'll get it

**Comment by suntereo** [comment]
rpetrich & chpwn... ProSwitcher is THE NEXT KILLER APP for the iPhone.  Thank you for the hard work you're putting into this.  I just discovered this bug when I went from FW 3.0 to 3.1.2 this eve.  I'm so happy to see that you're on top of all this and I'm sure you'll get these issues worked out.  You might even catch the eye of Apple... because this functionality is so dang cool.  Thanks again.
