### ISSUE TITLE
safe mode( itouch)

### ISSUE THREAD

**Issue by warcopolo** [rpetrich/ProSwitcher#70]
it's my mate's issue:
when he play games or open apps for a while,itouch will go to safe mode...

**Comment by rpetrich** [comment]
Can he post a crash dump generated with Crash Reporter? Also, does this still happen on v0.7.2?

**Comment by warcopolo** [comment]
he hasnt answered me yet....

**Comment by warcopolo** [comment]
fixed in 0.7.3

**Comment by rpetrich** [comment]
Excellent!
