### ISSUE TITLE
Seperate Landscape & Portrait Mode

### ISSUE THREAD

**Issue by politicalslug** [rpetrich/ProSwitcher#71]
Firstly, Proswitcher is very well coded and without any (as yet) encountered flaws.

However, proswitcher assumes the best approach to multitasking is to show just one app at a time with only one/eighth of the next app showing (not enough to distinguish which app that might be as it's just a tiny sliver). Couple that with having to swipe across each preview because only one can be seen at a time, and you end up with an unintuitive and stressful approach to multitasking. Palm's 'cards' approach allows you to zoom out and rearrange the 'cards', (allowing around 5-6 cards to be viewed at a time) is that something you'll likely implement in the future?  My problem is that if you have 10 apps running, and you need to get from the first to the last, you have to swipe nine times. With coverflow that could be accomplished in just two short swipes and in about a third or less the time. I don't believe for a second you actually believe proswitcher's single 'card' (without anything other visible apps shown) is a better approach than coverflow's ability to show many items on one page. Your approach causes too much time to be spent swiping. That's just silly.

Are you just being obstinate or are you messing with me? (asked in response to chpwn "cause I hate coverflow")

Also, how about the Landscape only mode, with either Kirikae allowed for Portrait mode, or you adding in a substitute with icons and text only?

Here is my suggestion: employ (at least optionally) a Kirikae like interface for portrait (without previews, just icons and text) and then invoke Coverflow view for landscape mode (turning the phone on its side). Since coverflow only allows so much viewing area in portrait mode, another option could be to shrink each preview window, with the option to zoom in if you hover (hold for a second) on the preview. Additionally, perhaps a rubberband approach would be better than having to flick for each preview window (like a hard swipe sends you across multiple previews instead of just to the next in line).

**Comment by rpetrich** [comment]
Cards are on the roadmap, but not necessarily soon; we have stability & integration issues to work out first.
Coverflow won't be implemented in mainline.
Landscape is not on our to do list, but we will accept patches that add it if they're of sufficient quality.

Since 90% of this is identical to your previous issue, I am closing this.
