### ISSUE TITLE
Respring animation every app close

### ISSUE THREAD

**Issue by ejoya** [rpetrich/ProSwitcher#72]
Closing apps in Proswitcher seems to show a respring animation, this causes a bit of lag. Is there a way to close apps without this animation?

**Comment by rpetrich** [comment]
A little lag will always be there as closing an app is nontrivial, but thanks to comex, 0.7.2 has gotten much better in this regard. I'm closing this one as completed :)

**Comment by rpetrich** [comment]
Actually closing
