### ISSUE TITLE
Enabling corner radius slows down the phone

### ISSUE THREAD

**Issue by ejoya** [rpetrich/ProSwitcher#73]
I'm on iPhone 3G and if I use a small/large corner radius, the animations gets jerky and phone lags. The larger the corner radius, the lag is more pronounced.

**Comment by rpetrich** [comment]
Corner radius imposes a cost as the layers have to be masked on the fly (they could be pre-computed, but that would destroy future plans to have live screenshot updates)

Large radius should be no slower than small radius though. Can you confirm this?

**Comment by ejoya** [comment]
Well I already disabled it because there is so much difference in speed between off and small/large. If it's not a bug and simply my phone cannot run it at good speed then it's fine the way it is. thanks

**Comment by ejoya** [comment]
yes.. its a bit more laggy when I used large compared to small

**Comment by rpetrich** [comment]
Are you sure you are using 0.7.2 and not the earlier/leaked 0.6 version?
Enabling rounded corners has a cost, but the cost is the same no matter the radius (we precompute a mask and then have the GPU composite that)

**Comment by ejoya** [comment]
sorry I was using the public beta 0.7 from your tweet.. upgrading now to 0.72

**Comment by ejoya** [comment]
using 0.72 and it's ok now same lag small or large but definitely not as good as without. thanks ryan for the patience

**Comment by GabsNL** [comment]
Can confirm same lag with small and large on version 0.7.2

**Comment by rpetrich** [comment]
Okay, great. This is as designed; rounded corners are necessarily slower :(

Closed.
