### ISSUE TITLE
Phone respring animation when closing an app in Proswitcher

### ISSUE THREAD

**Issue by ejoya** [rpetrich/ProSwitcher#74]
If I close an app using pro switcher (swiping or pushing x button) the background in the springboard seems to respring and produces lag. I'm using a 5 x 5 springboard icons in iPhone 3G. Is there a way to close the app in proswitcher without this respring animation or is it part of the program?

**Comment by rpetrich** [comment]
Upgrade to 0.7.2 and let me know how it goes
