### ISSUE TITLE
Springboard crashed due to many apps opened on iPhone 3G (v.0.7.2)

### ISSUE THREAD

**Issue by Didit** [rpetrich/ProSwitcher#75]
I noticed that when I have few apps opened, which are using quite amount of memory, my springboard got crashed. This didn't happen with v.0.6. On v0.6, if I opened many apps and memory went down to around 5 MB, somehow one of the app was closed automatically to prevent crashing springboard.

**Comment by Lowkey** [comment]
Solution: Don't do that.

**Comment by rpetrich** [comment]
Closing automatically is a feature of SpringBoard. Crashing is a bug of ProSwitcher. As always, post crash logs to get crash bugs fixed

**Comment by ejoya** [comment]
@lowkey it shouldn't crash the springboard if it's low in memory.

**Comment by Didit** [comment]
I'll do that :)

**Comment by rpetrich** [comment]
Didit claimed this was fixed in IRC
