### ISSUE TITLE
StatusBar coming back too slow when opening an app.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#76]
[ProSwitcher 0.7.2]
[iPhone 3G FW: 3.1.2]

When opening an app with a 'grey' statusbar the zoom animation invokes but the statusbar seems to zoom too late and overlaps on the 'old' statusbar of the ScreenShot.

I managed to capture it on screen (midway trough the animation): http://img130.imageshack.us/img130/4529/img0222.png

**Comment by rpetrich** [comment]
It's not too slow, but it animates from the wrong position.
Thanks for documenting this; it's a known issue, but now that it's up here it won't be forgotten
