### ISSUE TITLE
Badge from iPod is displayed, even with Backgrounder setting to hide badges on default apps.

### ISSUE THREAD

**Issue by Thyraz** [rpetrich/ProSwitcher#79]
Hi,

I set the Badges to be hidden in Backgrounder, and this works fine normally.
If I open the iPod app, close it the normal way, the badge is hidden while the iPod is running in background.

But if I open the iPod and then switch to another app with multiflow, there's a backgrounder badge appearing on the iPod icon.

**Comment by rpetrich** [comment]
This could be a bug in backgrounder; would need more information + screenshots. Also, this is ProSwitcher, not multifl0w ;)

**Comment by Thyraz** [comment]
If I switch from iPod to another App using Kirikae instead of ProSwitcher (I only have one of both Extensions running, the other is deactivated using SBSettings.)
the badge is still hidden as it should.

So 
a) kirikae has a feature that relies on the setting in Backgrounder that is not present in ProSwitcher
b) there's a bug in ProSwitcher :P

The badge only appears if you switch out of the running iPod App using ProSwitcher.
As long as you leave the app through the home-button this doesn't happen, even with ProSwitcher installed and active.

Once the badge appeared, there's no way to get rid of it through reopen/closing the iPod App.
Only killing the iPod App (or a respring of course :P) will help.

Some pictures:
1) Springboard after respring
http://drp.ly/4Tgn+

2) open the iPod App
http://drp.ly/4ThM+

3) active ProSwitcher inside of the iPod App. You can already see the badge in the background.
http://drp.ly/4Ti2g+

4) killed the iPod app inside ProSwitcher, the badge is gone.
http://drp.ly/4TjdI+

Sry about the multifl0w :P

**Comment by rpetrich** [comment]
Technically a bug in Backgrounder, but I've commited a workaround to unstable
