### ISSUE TITLE
Feature: Smoother transition animation

### ISSUE THREAD

**Issue by lifeexpired** [rpetrich/ProSwitcher#80]
Although this is a planned feature i'm just posting it on here so it dosen't get forgotten about and users can discuss.

The animation when changing between proswitcher and the apps and vise-versa isn't very smooth.

Also maybe an option to disable the animations?

**Comment by rpetrich** [comment]
Postponed until I get back from vacation (unless chpwn tackles it)

**Comment by rpetrich** [comment]
Completed in next release. It's not 100% as I want it to be, but...

**Comment by Mike11** [comment]
I like the idea of an option to disable the animations, if this would speed up ProSwitcher even a little bit.

**Comment by grp** [comment]
No it wouldn't.

**Comment by knoopx** [comment]
animation is specially choppy on ipad

**Comment by rpetrich** [comment]
Disable rounded corners.  Also, having a ton of applications open will reduce the launch speed.
