### ISSUE TITLE
Cannot Remove Page Dots

### ISSUE THREAD

**Issue by Sonola777** [rpetrich/ProSwitcher#81]
Even after Page Dots have been set to off in preferences they still show up. Also at the moment, when the Dock is set to off the dots are placed too low, they should be placed just underneath the Application Titles.

**Comment by gjtech** [comment]
I can confirm that page dots cannot be disabled even after switching it off in app settings.

**Comment by Sonola777** [comment]
Ok, since they cant be removed, can they at least be moved higher i.e. just underneath the Application Title? At the moment they're placed way too low when the Dock is turned off.
