### ISSUE TITLE
uMonitor dosen't background properly

### ISSUE THREAD

**Issue by lifeexpired** [rpetrich/ProSwitcher#82]
This worked fine in 0.72 i think, but in 0.73 it seems to go into the background but ProSwitcher dosen't show anything for it apart from a blank space where there should be an app? No way of exiting or opening it though, my other apps background properly..

Also, if theres an app backgrounded infront of it and I exit that one so the tile moves along to replace it, it shows up properly then.

**Comment by sysrage** [comment]
Same with WoW Authenticator. No name, no icon, no screenshot, no close button. But there's a page dot! :P
