### ISSUE TITLE
Memory Management

### ISSUE THREAD

**Issue by lifeexpired** [rpetrich/ProSwitcher#83]
When i'm backgrounding using Kirkae it uses 10-15mb less memory than ProSwitcher i've noticed, I don't know if this is entirely ProSwitchers fault but it does seem to use more memory than i'd expect it too use.

**Comment by rpetrich** [comment]
Not a bug. PreSwitcher must store screenshots for each active application and has a much more complicated view layout to maintain. When your device runs low on memory ProSwitcher will release all the memory it can and persist the majority of the rest of it to disk
