### ISSUE TITLE
Icon disappeared when added to folder - Categories App v2.29

### ISSUE THREAD

**Issue by blackemera** [rpetrich/ProSwitcher#84]
No longer in springboard or folder. ProSwitch app 
still working great...

**Comment by rpetrich** [comment]
Much more information needed

**Comment by GabsNL** [comment]
Can confirm this: When using Categories.app to add the ProSwitcher app to a category it removes it from SpringBoard but doesn't add it to the category.

**Comment by DannyNemer** [comment]
The same thing happens to Orbit (and probably OverBoard). It might have to do with the fact that they aren't "actual" apps but mainly activators, which means this is probably on Categories' end.

**Comment by rpetrich** [comment]
Looks like Categories' bug.

Closing as won't fix
