### ISSUE TITLE
Badge idea

### ISSUE THREAD

**Issue by sagitt** [rpetrich/ProSwitcher#86]
Add badge to top right of card... like screenshot!

http://img526.imageshack.us/img526/8973/2copia.png

(sorry for bad photoshop xD)

**Comment by rpetrich** [comment]
Probably won't implement this as most applications update their badge icon on exit (which means it's impossible to know what the badge should actually be in the general case)

**Comment by sagitt** [comment]
kirikae have this option.. or was the old backgrounder-integrated task manager?

**Comment by GabsNL** [comment]
No, Kirikae still has this option.
Actually a lot of apps update their app while your still in it or when you not even in it.
Example: Reeder, BeejiveIM, Hyves, AppStore, Mail
Not sure if it's a good idea do, just wanted to point that out.

**Comment by grp** [comment]
I think this is a good idea. I'll take a quick look into it.

**Comment by verzel** [comment]
AIM and Facebook also update the badge while backgrounded.  Great idea!

**Comment by grp** [comment]
Pushed badge support to unstable!

**Comment by GabsNL** [comment]
Nice! That was really quick chpwn :)
I'm anxiously awaiting the stable release of unstable.

**Comment by rpetrich** [comment]
/me awaits the "Badge Icons" don't update bug report :P

**Comment by grp** [comment]
:P
