### ISSUE TITLE
Backgrounder send-background action replacement

### ISSUE THREAD

**Issue by sagitt** [rpetrich/ProSwitcher#87]
with new beta of proswitcher the user can send apps in background by double tap to home button (or other methods) while it running.. why you don't add another activation method for "send in background only"? i think that backgrounder popup "background enable\disable" have bad look. and you can do the send-in-background action better ^^

**Comment by grp** [comment]
Ask ashikase to do this in backgrounder, that is unrelated to ProSwitcher.
