### ISSUE TITLE
Make the right and left card directly selectable

### ISSUE THREAD

**Issue by Mike11** [rpetrich/ProSwitcher#90]
Feature request: Make the right and left card directly selectable.  

Maybe via an option to show more of the left and right card (either move them closer together or zoom out more) and make the partially shown card selectable. So if you just want to switch back to your previous app you don't have to swipe and tap but can tap directly. Maybe offer it as a third option (one card, three cards, three cards plus).

**Comment by rpetrich** [comment]
We might implement an option to zoom out when holding on a card, but I don't think we'll implement as you've described
