### ISSUE TITLE
ProSwitcher SB Icon

### ISSUE THREAD

**Issue by gjtech** [rpetrich/ProSwitcher#91]
The SB Icon should be optional like Overboard. Since there are many ways to activate ProSwitcher, no need for springboard icon.

**Comment by grp** [comment]
Just use SBSettings.

**Comment by gjtech** [comment]
I do. But it would be rad if we didn't have to. Actually, like Overboard, 'Springboard Icon' should be an activation method. Please consider it.

That's just my input as a beta tester.

**Comment by rpetrich** [comment]
I will eventually pull in the code from OverBoard for this after I clean it up.
