### ISSUE TITLE
New App Tab for Proswitcher

### ISSUE THREAD

**Issue by Jacobahalls** [rpetrich/ProSwitcher#93]
When I look at ProSwitcher & Multifl0w, I always think about the Pages tab in Safari app.
When you go to the Pages tab in safari there is a "New Page" tab at the bottom. Now my thought, would it be possible for you to add a tab that said,"New App" or something like that, and when you press it a menu or something pops up of all of you're apps, and when you find you're app, you press it, it opens up and it puts it in the background aswell.

I love ProSwitcher!!!

**Comment by GabsNL** [comment]
I think the 'New App' button should be a 'Favourites' button.
I have heard of people having more then 200+ apps on their device and scrolling through that would be a pain. I do like your idea and would love to see it happen but rpetrich said he doesn't want to add buttons to ProSwitcher for esthetic reasons. Hopefully he or chpwn will reconsider or come up with a new idea.

**Comment by rpetrich** [comment]
Closed on the esthetic reasons

<sub>Also, it cannibalizes OverBoard :P</sub>

**Comment by sysrage** [comment]
all you gotta do is put Stack in your dock ;)
