### ISSUE TITLE
Tile the running apps

### ISSUE THREAD

**Issue by lifeexpired** [rpetrich/ProSwitcher#94]
Similar too the way Orbit displays pages, but running apps?

**Comment by GabsNL** [comment]
Kinda like what Steven Throughton-Smith posted on Twitter?
Image: http://twitpic.com/m1riw/full
Sounds like a totally different kind of app to me.
ProSwitcher is open source so if any other dev want to make an alt. UI for it I guess it could be possible.

**Comment by rpetrich** [comment]
Yeah, we don't have plans to implement something like this.

Feel free to fork; we'll accept patches/pull requests if they integrate well :)
