### ISSUE TITLE
ProSwitcher won't open

### ISSUE THREAD

**Issue by noraa** [rpetrich/ProSwitcher#95]
The ProSwitcher configuration simply won't open.  Click on the application icon, opens for a brief second and the closes immediately.  Have uninstalled Kirikae and restarted the phone, same problem.

iPhone 3G jailbroken and unlocked - various MobileSubtrate plugins and Rock Extensions installed:
Intellidial, Intelliscreen
Activator, Backgrounder, BatteryControl, Bosspaper, Categoriessb, Clockhide, Cydelete, Fiveicondock, Kirikae, Libhide, Lockinfo, Mailtoattachment, Mapsenhancer, Mobilevolumesound, Multiconmover, Musicbar, Musiccontrols, Notifier, Pogoplank, Preferenceloader, Priacy, Quickscroll, Reflectivedock, Rotationinhibitor, Sbsettings, Smshelper

**Comment by grp** [comment]
First, remove Rock Extensions. Really. Its horrible. It will mess up your device for no reason.

Then, get rid of IntelliScreen and IntelliDial and try again: those are known to cause many issues, everywhere.

**Comment by noraa** [comment]
Interesting, have had Rock Extensions for a while now, as well as both IntelliScreen and IntelliDial since before they were transferred to Rock, and have experienced no problems with them.

In any case, for the hell of it I removed all of them, reinstalled ProSwitcher - and not entirely unsurprisingly, still doesn't work.

**Comment by DannyNemer** [comment]
If I might add, may be you could try removing a bunch of extensions either way. 28 extensions sounds like far too many, and considering you are using an iPhone 3G, it is incontrovertibly taking up a ton of memory, which might not be allowing ProSwitcher to launch.

**Comment by ckong** [comment]
noraa: I noticed you have CategoriesSB installed.  If you have PS 0.7.3 in a folder, it won't open.  You'll have to put PS on the SpringBoard for now to make its icon work.

**Comment by noraa** [comment]
@DannyNemer: I do need to go through everything I have installed and see what I need/don't need anymore.  With that said, however, even with that many extensions the phone runs great.  If I restart it does take a while to boot up, but once it's up and running all is good.  I use Kirikae currently and have no problems with it whatsoever, and I also tried the trial of multifl0w (didn't like it) and it also worked.  So I doubt that many extensions would cause the config app to simply not open.

@ckong: I did read about PS not working in a Categories folder with CategoriesSB installed - as such I have made sure that it is located on my SpringBoard directly.

**Comment by noraa** [comment]
Just updated to 0.8 same issues

**Comment by noraa** [comment]
Well I figured it out!  Went through the process of disabling ALL of my MS extensions and then renabling one at a time.  Long story short, when disabled I was able to get ProSwitcher to work - until I reenabled LockInfo.  Then bam, clicking the ProSwitcher app icon does nothing.  Fortunately I am still able to enable it via other methods.  In any case, reported this issue to the LockInfo team as well.

**Comment by sysrage** [comment]
works great with lockinfo on my phone.

**Comment by noraa** [comment]
Well that's just weird...LockInfo was (is) causing problems for me with Stack v3 as well.  Maybe it's one of the plugins I have installed for it?  What plugins are you currently using with LockInfo?  I have Calendar, Clock, Mail, Phone, SMS and the Appigo Todo plugin.

**Comment by DannyNemer** [comment]
I use LockInfo and I too am having no problems.

**Comment by grp** [comment]
noraa: based on that; it isn't lock info itself: proswitcher and stackv3 use the same way of detecting icon taps.

**Comment by sysrage** [comment]
i have lockinfo, proswitcher, and stackv3 installed. all work great together for me. i don't use any lockinfo plugins. i use a base lockinfo install with the gruppled theme. try removing some plugins.

**Comment by noraa** [comment]
Another update: completely uninstalled LockInfo and all of it's associated plugins - and then reinstalled just lockinfo.  Everything was working fine, then added the two additional plugins (Clock and Todo) one at a time...and lo and behold and everything is still working!  Very odd.
