### ISSUE TITLE
Cancelling voice control and dock

### ISSUE THREAD

**Issue by ghost** [rpetrich/ProSwitcher#96]
With Show Dock option on.

Using the hold the home button down for a short hold setting, if you keep holding it down and activate the voice control and then cancel the voice control the dock dims like the rest of the springboard and you can't use it.

**Comment by sysrage** [comment]
confirmed. happens for me too

**Comment by grp** [comment]
Buy me a 3GS and I'll fix it.

**Comment by rpetrich** [comment]
I think I should tackle this one
<sup>(as donations aren't even close to covering the cost of a 3G S)</sup>
