### ISSUE TITLE
short hold home prevents manually un-backgrounding apps

### ISSUE THREAD

**Issue by sysrage** [rpetrich/ProSwitcher#97]
if you have short hold home button set as an activation method, it more or less prevents you from being able to short hold home button to disable backgrounding on an app. i say more or less because if you let go of the button the instant the 'backgrounding disabled' popup shows, it works. but if you hold it a split second longer, proswitcher pops up and re-backgrounds the app. understand this is technically working as designed by both apps, but it's a little screwy in practice.

**Comment by grp** [comment]
You can just disable backgrounding by closing it in ProSwitcher :).

**Comment by likwidfuzion** [comment]
What you can (and should) do is go into Backgrounder settings and set the Control setting to None. That way, ProSwitcher will handle the backgrounding instead.

**Comment by sysrage** [comment]
Yep. That was suggested to me last night, and it definitely makes this all work much better. Glad this is a 'wont fix' now :)

**Comment by grp** [comment]
Closed!
