### ISSUE TITLE
Safari quitter and 0.73 proswitcher not compatible

### ISSUE THREAD

**Issue by ejoya** [rpetrich/ProSwitcher#98]
I'm using ashikase safari quitter to exit safari even if there are open pages. With kirikae, if I want to background safari, it will background the program without problem even if I have safari quitter. (this is fully compatible because they came from the same author). With proswitcher, even if I want to background safari, safari will quit. thanks

**Comment by ejoya** [comment]
I tested it again by uninstalling safari quitter and for some reason the same thing happens. It seems safari will refuse to background if it's only in blank page. It will only background if you start surfing.

**Comment by grp** [comment]
Thats because there is no reason for it to background on a blank page!

**Comment by grp** [comment]
Closed; not a bug.
