### ISSUE TITLE
Apps not being added to proswitcher

### ISSUE THREAD

**Issue by Scuba-xx** [rpetrich/ProSwitcher#99]
When trying to add most apps to proswitcher it adds it for a second then removes it from the cards.

**Comment by sysrage** [comment]
scuba: install backgrounder.. 
chpwn/rpetrich, make backgrounder a dependency yet? ;)

**Comment by Scuba-xx** [comment]
awesome, thanks, works now.

**Comment by grp** [comment]
Backgrounder should be a Suggests, not a Depends, since that is what it really is. Sadly, I don't think Cydia supports Suggests.

**Comment by grp** [comment]
Closed :).

**Comment by rpetrich** [comment]
Backgrounder is now a dependency; added for 0.7.5 (not perfect IMO, but the best solution we have currently)
